# Generated by Django 2.1.3 on 2019-03-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Simples')),
                ('double', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Dupla')),
                ('triple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Tripla')),
                ('fourth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quádrupla')),
                ('fifth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quíntupla')),
                ('sixth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Sêxtupla')),
                ('sixth_more', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Mais de  6')),
                ('seller_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Seller', verbose_name='Cambista Relacionado')),
            ],
            options={
                'verbose_name': 'Comissão do Cambista',
                'verbose_name_plural': 'Comissões dos Cambistas',
            },
        ),
        migrations.CreateModel(
            name='GeneralConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cotation_value', models.DecimalField(decimal_places=2, default=200, max_digits=30, verbose_name='Valor Máximo das Cotas')),
                ('min_number_of_choices_per_bet', models.IntegerField(default=1, verbose_name='Número mínimo de escolhas por Aposta')),
                ('max_reward_to_pay', models.DecimalField(decimal_places=2, default=50000, max_digits=30, verbose_name='Valor máximo pago pela Banca')),
                ('min_bet_value', models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da aposta')),
                ('max_bet_value', models.DecimalField(decimal_places=2, default=1000000, max_digits=30, verbose_name='Valor máximo da aposta')),
                ('min_cotation_sum', models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da cota total')),
                ('max_cotation_sum', models.DecimalField(decimal_places=2, default=100000, max_digits=30, verbose_name='Valor máximo da cota total')),
                ('percentual_reduction', models.IntegerField(default=100, verbose_name='Redução Percentual')),
                ('block_bets', models.BooleanField(default=False, verbose_name='Bloquear Apostas?')),
                ('auto_pay_punter', models.BooleanField(default=True, verbose_name='Auto Pagar Apostadores')),
            ],
            options={
                'verbose_name': 'Configurações Gerais',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.CreateModel(
            name='MarketReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_to_reduct', models.IntegerField(choices=[(600, 'Casa'), (601, 'Empate'), (602, 'Fora'), (1, '1X2'), (2, 'Abaixo/Acima'), (3, 'Asian Handicap'), (4, '1° Tempo/2° Tempo'), (5, 'Ímpar/Par'), (6, 'Placar Correto'), (7, 'Dupla Chance'), (9, 'Placar Correto 1° Tempo'), (13, 'Handicap Europeu'), (16, 'Primeiro Time a Marcar'), (17, 'Ambos marcam?'), (21, 'Abaixo/Acima 1° Tempo'), (25, 'Dupla Chance 1° Tempo'), (41, 'Vencedor 1° Tempo'), (42, 'Vencedor 2° Tempo'), (45, 'Abaixo/Acima 2° Tempo'), (52, 'Casa/Fora'), (56, 'Último time a marcar'), (61, 'Handicap Europeu 1° Tempo'), (62, 'Ímpar/Par 1° Tempo'), (64, 'Asian Handicap 1° Tempo'), (71, 'Metade com maior placar'), (73, '2° Tempo Ímpar/Par'), (79, 'Haverá Pênalti?'), (84, 'Vencer em ambas etapas'), (85, 'Ganhar de Virada'), (86, 'Vencer sem tomar Gol'), (98, 'Time de casa não toma gol?'), (99, 'Time de fora não toma gol?'), (101, 'Abaixo/Acima - Time de Casa'), (102, 'Abaixo/Acima - Time de Fora'), (113, 'Ambos marcam no 1° Tempo?'), (128, 'Número de Gols'), (134, 'Número de Gols 1° Tempo'), (143, 'Em qual etapa o time de Casa vai fazer mais Gols?'), (144, 'Em qual etapa o time de Fora vai fazer mais Gols?'), (149, 'Número de gols Casa'), (150, 'Número de Gols - Fora'), (161, 'Resultado aos 10 minutos'), (163, 'Número de Gols 2 ° Tempo'), (168, 'Vai ter gol contra?'), (169, 'Marcar em ambas etapas'), (171, 'Ganhar uma ou ambas etapas'), (198, 'Ímpar/Par - Time de Casa'), (199, 'Ímpar/Par - Time de Fora'), (211, 'Ambos marcam no 2° Tempo?'), (215, 'Time de fora vai marcar no 1° Tempo?'), (216, 'Time de fora vai marcar no 2° Tempo?'), (218, 'Time de casa marca no 1° tempo?'), (219, 'Time de casa marca 2° tempo?'), (427, 'Casa/Empate/Fora  Abaixo/Acima'), (429, 'Vencedor do Encontro e Ambos Marcam'), (433, 'European Handicap Corners'), (461, 'Margem de Vitória'), (523, 'Abaixo/Acima e Ambos marcam')], unique=True, verbose_name='Tipo de Aposta')),
                ('reduction_percentual', models.IntegerField(default=100, verbose_name='Percentual de Redução')),
            ],
            options={
                'verbose_name': 'Redução de Cota',
                'verbose_name_plural': 'Reduções de Cotas',
            },
        ),
        migrations.CreateModel(
            name='MarketRemotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_to_remove', models.IntegerField(choices=[(2, 'Abaixo/Acima'), (21, 'Abaixo/Acima 1° Tempo'), (45, 'Abaixo/Acima 2° Tempo'), (101, 'Abaixo/Acima - Time de Casa'), (102, 'Abaixo/Acima - Time de Fora')], verbose_name='Tipo de Aposta')),
                ('below_above', models.CharField(choices=[('Abaixo', 'Abaixo'), ('Acima', 'Acima')], max_length=8, verbose_name='Abaixo ou Acima')),
                ('base_line', models.CharField(max_length=5, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Remoção de Aposta',
                'verbose_name_plural': 'Remoção de Apostas',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.BooleanField(default=True, verbose_name='Gerar Visão Geral')),
            ],
            options={
                'verbose_name': 'Visão Geral - Caixa',
                'verbose_name_plural': 'Visão Geral - Caixa',
            },
        ),
        migrations.CreateModel(
            name='RewardRelated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value_max', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor da Aposta')),
                ('reward_value_max', models.DecimalField(decimal_places=2, default=100000, max_digits=30, verbose_name='Valor Máximo da Recompensa')),
            ],
            options={
                'verbose_name': 'Limitar Prêmios',
                'verbose_name_plural': 'Limitação de Prêmios',
            },
        ),
        migrations.CreateModel(
            name='RulesMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=999999, verbose_name='Texto de Regras')),
            ],
            options={
                'verbose_name': 'Texto de Regras',
                'verbose_name_plural': 'Texto de Regras',
            },
        ),
        migrations.CreateModel(
            name='TicketCustomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Mensagem customizada')),
            ],
            options={
                'verbose_name': 'Texto do Ticket',
                'verbose_name_plural': 'Texto do Ticket',
            },
        ),
    ]
