# Generated by Django 2.0.5 on 2018-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cotation_value', models.FloatField(default=200, verbose_name='Valor Máximo das Cotas')),
                ('min_number_of_choices_per_bet', models.IntegerField(default=1, verbose_name='Número mínimo de escolhas por Aposta')),
                ('max_reward_to_pay', models.FloatField(default=50000, verbose_name='Valor máximo pago pela Banca')),
                ('min_bet_value', models.FloatField(default=1, verbose_name='Valor mínimo da aposta')),
                ('percentual_reduction', models.IntegerField(default=100, verbose_name='Redução Percentual')),
            ],
            options={
                'verbose_name': 'Configurar Restrições',
                'verbose_name_plural': 'Configurar Restrições',
            },
        ),
    ]
