# Generated by Django 2.1.3 on 2019-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_1741'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketreduction',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketremotion',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardrelated',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulesmessage',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketcustommessage',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
    ]
