# Generated by Django 2.0.6 on 2018-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_cotation_value',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=30, verbose_name='Valor Máximo das Cotas'),
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_reward_to_pay',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=30, verbose_name='Valor máximo pago pela Banca'),
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='min_bet_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da aposta'),
        ),
    ]
