# Generated by Django 2.0.6 on 2018-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20180613_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Visão Geral',
                'verbose_name_plural': 'Visão Geral',
            },
        ),
    ]
