# Generated by Django 2.1.7 on 2019-03-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20190313_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalconfigurations',
            old_name='percentual_reduction',
            new_name='cotations_percentage',
        ),
    ]
