# Generated by Django 2.0.6 on 2018-10-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rewardrelated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardrelated',
            options={'verbose_name': 'Limitar Prêmios', 'verbose_name_plural': 'Limitação de Prêmios'},
        ),
        migrations.AlterField(
            model_name='rewardrelated',
            name='general_configurations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_related', to='utils.GeneralConfigurations'),
        ),
        migrations.AlterField(
            model_name='rewardrelated',
            name='value_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor da Aposta'),
        ),
    ]
