# Generated by Django 2.1.7 on 2019-03-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190323_1300'),
        ('utils', '0003_auto_20190322_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_excluded_games', to='core.Store')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.League')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_excluded_leagues', to='core.Store')),
            ],
        ),
    ]
