# Generated by Django 2.0.6 on 2018-10-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20181026_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrelated',
            name='general_configurations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_related', to='utils.GeneralConfigurations'),
        ),
    ]
