# Generated by Django 2.1.7 on 2019-03-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190323_1300'),
        ('utils', '0004_excludedgames_excludedleague'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcludedGames',
            new_name='ExcludedGame',
        ),
    ]
