# Generated by Django 2.0.6 on 2018-06-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_overview_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='overview',
        ),
    ]
