# Generated by Django 2.1.7 on 2019-03-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20190325_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludedleague',
            old_name='game',
            new_name='league',
        ),
    ]
