# Generated by Django 2.0.6 on 2018-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_rewardrelated_general_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=75)),
            ],
        ),
    ]
