# Generated by Django 2.0.6 on 2018-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_overview_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='overview',
            field=models.BooleanField(default=True, verbose_name='Gerar Visão Geral'),
        ),
    ]
