# Generated by Django 2.0.6 on 2018-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_marketreduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreduction',
            name='market_to_reduct',
            field=models.IntegerField(choices=[(1, 'Vencedor do Encontro'), (10, 'Casa/Visitante'), (37, 'Vencedor do Primeiro Tempo'), (80, 'Vencedor do Segundo Tempo'), (976334, 'Resultado/Total de Gol(s)'), (975916, 'Resultado Exato no Primeiro Tempo'), (975909, 'Resultado Exato do Jogo'), (976241, 'Número Exato de Gol(s)'), (59, 'Os Dois Times Marcam'), (976360, 'Time Visitante Marca'), (976348, 'Time da Casa Marca'), (976096, 'Time da Casa NÃO Tomará Gol(s)'), (8594683, 'Time Visitante NÃO Tomará Gol(s)'), (976204, 'Total de Gols do Visitante'), (976198, 'Total de Gols da Casa'), (12, 'Total de Gol(s) no Encontro, Acima/Abaixo'), (47, 'Total de Gol(s) no Segundo Tempo, Acima/Abaixo'), (38, 'Total de Gols do Primeiro Tempo, Acima/Abaixo'), (976144, 'Etapa com Mais Gol(s)'), (976316, 'Resultado/2 Times Marcam'), (976193, 'Vencedor nas Duas Etapas'), (63, 'Dupla Chance'), (976236, 'Vencer e não tomar Gol(s)'), (975930, 'Placar Impar/Par')], max_length=10, unique=True, verbose_name='Tipo de Aposta'),
        ),
        migrations.AlterField(
            model_name='marketreduction',
            name='reduction_percentual',
            field=models.IntegerField(default=100, verbose_name='Percentual de Redução'),
        ),
    ]
