# Generated by Django 2.0.6 on 2018-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20181029_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcustommessage',
            name='text',
            field=models.TextField(max_length=75, verbose_name='Mensagem customizada'),
        ),
    ]
