# Generated by Django 2.1.7 on 2019-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_generalconfigurations_max_number_of_choices_per_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_number_of_choices_per_bet',
            field=models.IntegerField(default=50, verbose_name='Número máximo de escolhas por Aposta'),
        ),
    ]
