# Generated by Django 2.1.7 on 2019-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20190327_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='alert_bet_value',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=30, verbose_name='Valor de alerta para apostas'),
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='min_cotation_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da cota total_revenuel'),
        ),
    ]
