# Generated by Django 2.1.2 on 2018-10-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20181029_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=999999, verbose_name='Texto de Regras')),
            ],
            options={
                'verbose_name': 'Texto de Regras',
                'verbose_name_plural': 'Texto de Regras',
            },
        ),
    ]
