# Generated by Django 2.0.6 on 2018-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20180707_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='auto_pay_punter',
            field=models.BooleanField(default=False, verbose_name='Auto Pagar Vencedores'),
        ),
    ]
