# Generated by Django 2.1.7 on 2019-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20190327_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreduction',
            name='market_to_reduct',
            field=models.CharField(choices=[('Total de Gols', 'Total de Gols'), ('Resultado / Total de Gols', 'Resultado / Total de Gols'), ('Total de Gols / Ambos  Marcam', 'Total de Gols / Ambos  Marcam'), ('Total de Gols Exato', 'Total de Gols Exato'), ('Número de Gols na Partida', 'Número de Gols na Partida'), ('Ambos Marcam', 'Ambos Marcam'), ('Times que Marcam', 'Times que Marcam'), ('Time Casa - Total de Gols Exato', 'Time Casa - Total de Gols Exato'), ('Time Fora - Total de Gols Exato', 'Time Fora - Total de Gols Exato'), ('Resultado 1° Tempo / Ambos Marcam', 'Resultado 1° Tempo / Ambos Marcam'), ('Resultado 1° Tempo / Total de Gols', 'Resultado 1° Tempo / Total de Gols'), ('Ambos Marcam 1° Tempo', 'Ambos Marcam 1° Tempo'), ('Ambos Marcam 2° Tempo', 'Ambos Marcam 2° Tempo'), ('Ambos Marcam 1° e 2° Tempo', 'Ambos Marcam 1° e 2° Tempo'), ('Total de Gols 1° Tempo', 'Total de Gols 1° Tempo'), ('Total de Gols Exato 1° Tempo', 'Total de Gols Exato 1° Tempo'), ('Haverá Gol', 'Haverá Gol'), ('Etapa com mais Gols', 'Etapa com mais Gols'), ('Resultado 2° Tempo', 'Resultado 2° Tempo'), ('Total de Gols - 2° Tempo', 'Total de Gols - 2° Tempo'), ('Total de Gols Exato 2°  Tempo', 'Total de Gols Exato 2°  Tempo'), ('Resultado / Ambos Marcam', 'Resultado / Ambos Marcam'), ('Margem de Vitória', 'Margem de Vitória'), ('Especiais', 'Especiais')], max_length=100, unique=True, verbose_name='Tipo de Aposta'),
        ),
    ]
