# Generated by Django 2.1.2 on 2018-11-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20181031_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketreduction',
            options={'verbose_name': 'Redução de Cota', 'verbose_name_plural': 'Reduções de Cotas'},
        ),
    ]
