# Generated by Django 2.0.7 on 2018-08-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_manager_can_sell_unlimited'),
        ('utils', '0010_generalconfigurations_auto_pay_punter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.IntegerField(default=4, verbose_name='Apostas Simples')),
                ('double', models.IntegerField(default=6, verbose_name='Apostas Duplas')),
                ('triple_amount', models.IntegerField(default=8, verbose_name='Apostas Triplas')),
                ('four_plus_amount', models.IntegerField(default=10, verbose_name='Quatro Apostas ou Mais')),
                ('seller_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Seller', verbose_name='Vendedor Relacionado')),
            ],
            options={
                'verbose_name': 'Comissão do Vendedor',
                'verbose_name_plural': 'Comissões dos Vendedores',
            },
        ),
    ]
