# Generated by Django 2.1.7 on 2019-04-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190404_1623'),
        ('utils', '0010_auto_20190408_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
    ]
