# Generated by Django 2.1.3 on 2018-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20181101_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcustommessage',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Mensagem customizada'),
        ),
    ]
