# Generated by Django 2.0.7 on 2018-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='four_plus_amount',
            field=models.IntegerField(default=10, verbose_name='Mais de 3'),
        ),
    ]
