# Generated by Django 2.2 on 2019-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_comission_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='min_cotation_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da cota total'),
        ),
    ]
