# Generated by Django 2.0.7 on 2018-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_auto_20180827_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='min_cotation_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor mínimo da cota total'),
        ),
    ]
