# Generated by Django 2.1.3 on 2018-11-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_auto_20181105_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrelated',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
