# Generated by Django 2.2.1 on 2019-05-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190517_1620'),
        ('utils', '0013_auto_20190516_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor da Aposta')),
                ('max_reward_value', models.DecimalField(decimal_places=2, default=100000, max_digits=30, verbose_name='Valor Máximo da Recompensa')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Limitador de Prêmio',
                'verbose_name_plural': 'Limitador de Prêmios',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='cotations_percentage',
            field=models.IntegerField(default=100, verbose_name='Ajuste das Cotas'),
        ),
        migrations.DeleteModel(
            name='RewardRelated',
        ),
    ]
