# Generated by Django 2.0.7 on 2018-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_generalconfigurations_min_cotation_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='double',
            field=models.IntegerField(default=10, verbose_name='Apostas Duplas'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='simple',
            field=models.IntegerField(default=10, verbose_name='Apostas Simples'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='triple_amount',
            field=models.IntegerField(default=10, verbose_name='Apostas Triplas'),
        ),
    ]
