# Generated by Django 2.1.7 on 2019-05-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190517_1620'),
        ('utils', '0014_auto_20190517_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketreduction',
            name='market_to_reduct',
        ),
        migrations.AddField(
            model_name='marketreduction',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_reduction', to='core.Market', verbose_name='Tipo de Aposta'),
            preserve_default=False,
        ),
    ]
