# Generated by Django 2.1 on 2018-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_auto_20180830_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='max_cotation_sum',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=30, verbose_name='Valor máximo da cota total'),
        ),
    ]
