# Generated by Django 2.1.3 on 2018-11-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_auto_20181105_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcustommessage',
            options={'verbose_name': 'Texto do Ticket', 'verbose_name_plural': 'Texto do Ticket'},
        ),
    ]
