# Generated by Django 2.1.3 on 2018-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20181106_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreduction',
            name='market_to_reduct',
            field=models.IntegerField(choices=[(100, 'Casa'), (101, 'Empate'), (102, 'Fora'), (1, '1X2'), (2, 'Abaixo/Acima'), (3, 'Asian Handicap'), (4, '1° Tempo/2° Tempo'), (5, 'Ímpar/Par'), (6, 'Placar Correto'), (7, 'Dupla Chance'), (9, 'Placar Correto 1° Tempo'), (11, 'Total de Escanteios'), (13, 'Handicap Europeu'), (16, 'Primeiro Time a Marcar'), (17, 'Ambos marcam?'), (21, 'Abaixo/Acima 1° Tempo'), (25, 'Dupla Chance 1° Tempo'), (41, 'Vencedor 1° Tempo'), (42, 'Vencedor 2° Tempo'), (45, 'Abaixo/Acima 2° Tempo'), (52, 'Casa/Fora'), (56, 'Último time a marcar'), (61, 'Handicap Europeu 1° Tempo'), (62, 'Ímpar/Par 1° Tempo'), (64, 'Asian Handicap 1° Tempo'), (71, 'Metade com maior placar'), (73, '2° Tempo Ímpar/Par'), (79, 'Haverá Pênalti?'), (84, 'Vencer em ambas etapas'), (85, 'Ganhar de Virada'), (86, 'Vencer sem tomar Gol'), (95, 'Handicap - Escanteios'), (98, 'Time de casa não toma gol?'), (99, 'Time de fora não toma gol?'), (101, 'Abaixo/Acima - Time de Casa'), (102, 'Abaixo/Acima - Time de Fora'), (113, 'Ambos marcam no 1° Tempo?'), (128, 'Número de Gols'), (129, 'Abaixo/Acima Escanteios 1° Tempo'), (134, 'Número de Gols 1° Tempo'), (143, 'Em qual etapa o time de Casa vai fazer mais Gols?'), (144, 'Em qual etapa o time de Fora vai fazer mais Gols?'), (149, 'Número de gols Casa'), (150, 'Número de Gols - Fora'), (161, 'Resultado aos 10 minutos'), (163, 'Número de Gols 2 ° Tempo'), (168, 'Vai ter gol contra?'), (169, 'Marcar em ambas etapas'), (171, 'Ganhar uma ou ambas etapas'), (198, 'Ímpar/Par - Time de Casa'), (199, 'Ímpar/Par - Time de Fora'), (211, 'Ambos marcam no 2° Tempo?'), (215, 'Time de fora vai marcar no 1° Tempo?'), (216, 'Time de fora vai marcar no 2° Tempo?'), (218, 'Time de casa marca no 1° tempo?'), (219, 'Time de casa marca 2° tempo?'), (305, 'Escanteios Abaixo/Exatamente/Acima'), (427, 'Casa/Empate/Fora  Abaixo/Acima'), (429, 'Vencedor do Encontro e Ambos Marcam'), (433, 'European Handicap Corners'), (461, 'Margem de Vitória'), (523, 'Abaixo/Acima e Ambos marcam')], unique=True, verbose_name='Tipo de Aposta'),
        ),
    ]
