# Generated by Django 2.1.7 on 2019-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20190520_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketremotion',
            old_name='below_above',
            new_name='under_above',
        ),
        migrations.AlterField(
            model_name='marketremotion',
            name='market_to_remove',
            field=models.IntegerField(choices=[(1, 'Gols - Acima/Abaixo'), (2, 'Total de Gols'), (3, 'Resultado / Total de Gols'), (4, 'Total de Gols / Ambos  Marcam'), (6, 'Número de Gols na Partida'), (17, 'Resultado 1° Tempo / Total de Gols'), (22, 'Total de Gols 1° Tempo'), (30, 'Total de Gols 2° Tempo')], verbose_name='Tipo de Aposta'),
        ),
    ]
