# Generated by Django 2.1 on 2018-09-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_generalconfigurations_max_cotation_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_cotation_sum',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=30, verbose_name='Valor máximo da cota total'),
        ),
    ]
