# Generated by Django 2.1.7 on 2019-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_auto_20190523_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketreduction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
