# Generated by Django 2.2.1 on 2019-06-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190523_1743'),
        ('core', '0035_auto_20190517_1620'),
        ('utils', '0017_marketreduction_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerComission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Simples')),
                ('double', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Dupla')),
                ('triple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Tripla')),
                ('fourth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quádrupla')),
                ('fifth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quíntupla')),
                ('sixth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Sêxtupla')),
                ('sixth_more', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Mais de 6')),
                ('seller_related', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Seller', verbose_name='Cambista Relacionado')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Comissão do Cambista',
                'verbose_name_plural': 'Comissões dos Cambistas',
            },
        ),
        migrations.CreateModel(
            name='SellerComission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Simples')),
                ('double', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Dupla')),
                ('triple', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Tripla')),
                ('fourth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quádrupla')),
                ('fifth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Quíntupla')),
                ('sixth', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Sêxtupla')),
                ('sixth_more', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Mais de 6')),
                ('manager_related', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Manager', verbose_name='Gerente Relacionado')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Comissão do Gerentes',
                'verbose_name_plural': 'Comissões dos Gerentes',
            },
        ),
        migrations.DeleteModel(
            name='Comission',
        ),
    ]
