# Generated by Django 2.1 on 2018-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20180904_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='max_bet_value',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=30, verbose_name='Valor máximo da aposta'),
        ),
    ]
