# Generated by Django 2.1.3 on 2018-11-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20181107_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalconfigurations',
            name='auto_pay_punter',
        ),
    ]
