# Generated by Django 2.1.3 on 2018-11-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_remove_generalconfigurations_auto_pay_punter'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='block_bets',
            field=models.BooleanField(default=False, verbose_name='Bloquear Apostas?'),
        ),
    ]
