# Generated by Django 2.2.1 on 2019-06-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_auto_20190603_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managercomission',
            old_name='seller_related',
            new_name='manager_related',
        ),
        migrations.RenameField(
            model_name='sellercomission',
            old_name='manager_related',
            new_name='seller_related',
        ),
    ]
