# Generated by Django 2.1.3 on 2018-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_generalconfigurations_block_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='auto_pay_punter',
            field=models.BooleanField(default=True, verbose_name='Auto Pagar Apostadores'),
        ),
    ]
