# Generated by Django 2.2.1 on 2019-06-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_auto_20190603_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managercomission',
            name='manager_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Manager', verbose_name='Cambista Relacionado'),
        ),
        migrations.AlterField(
            model_name='sellercomission',
            name='seller_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='user.Seller', verbose_name='Gerente Relacionado'),
        ),
    ]
