# Generated by Django 2.2.1 on 2019-06-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_auto_20190603_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managercomission',
            options={'ordering': ('-pk',), 'verbose_name': 'Comissão do Cambista', 'verbose_name_plural': 'Comissões dos Cambistas'},
        ),
        migrations.AlterModelOptions(
            name='sellercomission',
            options={'ordering': ('-pk',), 'verbose_name': 'Comissão do Gerentes', 'verbose_name_plural': 'Comissões dos Gerentes'},
        ),
    ]
