# Generated by Django 2.1.3 on 2018-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_auto_20181122_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketremotion',
            options={'verbose_name': 'Remoção de Aposta', 'verbose_name_plural': 'Remoção de Apostas'},
        ),
        migrations.AlterField(
            model_name='marketremotion',
            name='below_above',
            field=models.CharField(choices=[('Abaixo', 'Abaixo'), ('Acima', 'Acima')], max_length=8, verbose_name='Abaixo ou Acima'),
        ),
        migrations.AlterField(
            model_name='marketremotion',
            name='market_to_remove',
            field=models.IntegerField(choices=[(2, 'Abaixo/Acima'), (21, 'Abaixo/Acima 1° Tempo'), (45, 'Abaixo/Acima 2° Tempo'), (101, 'Abaixo/Acima - Time de Casa'), (102, 'Abaixo/Acima - Time de Fora'), (427, 'Casa/Empate/Fora  Abaixo/Acima'), (523, 'Abaixo/Acima e Ambos marcam')], unique=True, verbose_name='Tipo de Aposta'),
        ),
    ]
