# Generated by Django 2.2.2 on 2019-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_managercomission_profit_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='bonus_by_won_ticket',
            field=models.IntegerField(default=10, verbose_name='Bônus por bilhetes premiados'),
        ),
    ]
