# Generated by Django 2.2.2 on 2019-06-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_generalconfigurations_bonus_by_won_ticket'),
        ('utils', '0023_auto_20190607_1459'),
    ]

    operations = [
    ]
