# Generated by Django 2.2.2 on 2019-06-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0031_auto_20190625_1433'),
        ('utils', '0031_auto_20190624_1759'),
    ]

    operations = [
    ]
