# Generated by Django 2.2.2 on 2019-07-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190702_1603'),
        ('utils', '0032_merge_20190625_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_configuration', to='core.Store'),
            preserve_default=False,
        ),
    ]
