# Generated by Django 2.2.2 on 2019-07-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_auto_20190702_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_configuration', to='core.Store'),
        ),
    ]
