# Generated by Django 2.2.3 on 2019-07-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_game_can_be_modified_by_api'),
        ('utils', '0035_auto_20190702_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
    ]
