# Generated by Django 2.2.3 on 2019-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0036_release_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='bonus_won_ticket',
            field=models.BooleanField(default=False, verbose_name='Ativar Bônus por bilhetes premiados?'),
        ),
    ]
