# Generated by Django 2.2.3 on 2019-07-26 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_auto_20190717_1135'),
        ('utils', '0037_generalconfigurations_bonus_won_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Release',
            new_name='Entry',
        ),
    ]
