# Generated by Django 2.2.3 on 2019-07-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0038_auto_20190726_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excludedgame',
            options={'ordering': ('-pk',), 'verbose_name': 'Jogo Removido', 'verbose_name_plural': 'Jogos Removidos'},
        ),
        migrations.AlterModelOptions(
            name='excludedleague',
            options={'ordering': ('-pk',), 'verbose_name': 'Liga Removida', 'verbose_name_plural': 'Ligas Removidas'},
        ),
        migrations.AlterModelOptions(
            name='marketreduction',
            options={'ordering': ('-pk',), 'verbose_name': 'Redução de Cota', 'verbose_name_plural': 'Reduções de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='marketremotion',
            options={'ordering': ('-pk',), 'verbose_name': 'Remoção de Aposta', 'verbose_name_plural': 'Remoção de Apostas'},
        ),
        migrations.AlterModelOptions(
            name='rulesmessage',
            options={'ordering': ('-pk',), 'verbose_name': 'Texto de Regras', 'verbose_name_plural': 'Texto de Regras'},
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
    ]
