# Generated by Django 2.2.3 on 2019-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190726_1220'),
        ('utils', '0039_auto_20190727_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketReduction',
            new_name='MarketModified',
        ),
    ]
