# Generated by Django 2.2.3 on 2019-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0040_auto_20190730_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketremotion',
            name='market_to_remove',
            field=models.IntegerField(choices=[(1, 'Gols - Acima/Abaixo'), (2, 'Total de Gols'), (3, 'Resultado / Total de Gols'), (4, 'Total de Gols / Ambos  Marcam'), (6, 'Número de Gols na Partida'), (16, 'Resultado 1° Tempo / Total de Gols'), (21, 'Total de Gols 1° Tempo'), (29, 'Total de Gols 2° Tempo')], verbose_name='Tipo de Aposta'),
        ),
    ]
