# Generated by Django 2.2.4 on 2019-08-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0041_auto_20190809_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalconfigurations',
            name='auto_pay_winners',
        ),
    ]
