# Generated by Django 2.2.3 on 2019-08-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0042_remove_generalconfigurations_auto_pay_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodified',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modification', to='core.Market', verbose_name='Tipo de Aposta'),
        ),
    ]
