# Generated by Django 2.2.3 on 2019-08-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0043_auto_20190812_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketmodified',
            old_name='active',
            new_name='available',
        ),
    ]
