# Generated by Django 2.2.3 on 2019-08-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0044_auto_20190812_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodified',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifications', to='core.Market', verbose_name='Tipo de Aposta'),
        ),
    ]
