# Generated by Django 2.2.4 on 2019-08-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0047_auto_20190829_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesmessage',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
        ),
        migrations.AlterField(
            model_name='ticketcustommessage',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
        ),
    ]
