# Generated by Django 2.2.4 on 2019-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0048_auto_20190829_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesmessage',
            name='text',
            field=models.TextField(blank=True, max_length=999999, null=True, verbose_name='Texto de Regras'),
        ),
        migrations.AlterField(
            model_name='ticketcustommessage',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mensagem customizada'),
        ),
    ]
