# Generated by Django 2.2.4 on 2019-08-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0049_auto_20190829_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcustommessage',
            options={'ordering': ('-pk',), 'verbose_name': 'Texto do Ticket', 'verbose_name_plural': 'Texto do Ticket'},
        ),
    ]
