# Generated by Django 2.2.4 on 2019-09-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0052_auto_20190904_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='add_league_to_ticket_print',
            field=models.BooleanField(default=False, verbose_name='Adicionar ligas nos envios do bilhete?'),
        ),
    ]
