# Generated by Django 2.2.4 on 2019-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0053_generalconfigurations_add_league_to_ticket_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='add_link_to_ticket_whats',
            field=models.BooleanField(default=True, verbose_name='Adicionar link do bilhete ao envio do whatsapp?'),
        ),
    ]
