# Generated by Django 2.2.4 on 2019-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0054_generalconfigurations_add_link_to_ticket_whats'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='after_tomorrow_games_available',
            field=models.BooleanField(default=True, verbose_name='Disponibilizar jogos de depois de amanhã?'),
        ),
        migrations.AddField(
            model_name='generalconfigurations',
            name='tomorrow_games_available',
            field=models.BooleanField(default=True, verbose_name='Disponibilizar jogos de amanhã?'),
        ),
    ]
