# Generated by Django 2.1.3 on 2019-03-13 17:40

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro Nome')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('cellphone', models.CharField(max_length=14, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('cellphone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='Endereço')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comissão')),
                ('credit_limit_to_add', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Crédito')),
                ('can_cancel_ticket', models.BooleanField(default=True, verbose_name='Cancela Bilhete ?')),
                ('limit_time_to_cancel', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='Tempo Limite de Cancelamento')),
                ('can_sell_unlimited', models.BooleanField(default=False, verbose_name='Vender Ilimitado?')),
                ('can_change_limit_time', models.BooleanField(default=False, verbose_name='Pode alterar tempo de Cancelamento do Cambista?')),
                ('based_on_profit', models.BooleanField(default=False, verbose_name='Calcular comissão baseado no líquido ?')),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'ordering': ('-pk',),
                'permissions': (('be_manager', 'Be a manager, permission.'),),
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cellphone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Apostador',
                'verbose_name_plural': 'Apostadores',
                'permissions': (('be_punter', 'Be a punter, permission.'),),
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('cellphone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='Endereço')),
                ('can_sell_unlimited', models.BooleanField(default=False, verbose_name='Vender Ilimitado?')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Crédito')),
                ('can_cancel_ticket', models.BooleanField(default=False, verbose_name='Cancela Bilhete ?')),
                ('limit_time_to_cancel', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='Tempo Limite de Cancelamento')),
            ],
            options={
                'verbose_name': 'Cambista',
                'verbose_name_plural': 'Cambistas',
                'ordering': ('-pk',),
                'permissions': (('be_seller', 'Be a seller, permission.'),),
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
