# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_user',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
