# Generated by Django 2.1.2 on 2018-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='limit_time_to_cancel',
            field=models.IntegerField(default=5, verbose_name='Tempo Limite de Cancelamento'),
        ),
    ]
