# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punter',
            options={'verbose_name': 'Apostador', 'verbose_name_plural': 'Apostadores'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
