# Generated by Django 2.1.2 on 2018-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='can_cancel_ticket',
            field=models.BooleanField(default=True, verbose_name='Cancela Bilhete ?'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='can_cancel_ticket',
            field=models.BooleanField(default=False, verbose_name='Cancela Bilhete ?'),
        ),
    ]
