# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171105_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='cpf',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
