# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171210_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
