# Generated by Django 2.1.3 on 2018-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181022_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='commission',
        ),
        migrations.AddField(
            model_name='manager',
            name='cellphone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='punter',
            name='cellphone',
            field=models.CharField(default='000', max_length=14, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='cellphone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
