# Generated by Django 2.0.1 on 2018-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seller_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='punter',
            name='cellphone',
            field=models.CharField(max_length=14, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='cellphone',
            field=models.CharField(max_length=14, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=75, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cellphone',
            field=models.CharField(max_length=14, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
