# Generated by Django 2.0.1 on 2018-01-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180121_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cotation_value', models.FloatField(null=True, verbose_name='Valor Máximo das Cotas')),
                ('min_number_of_choices_per_bet', models.IntegerField(default=0, verbose_name='Número mínimo de escolhas por Aposta')),
                ('max_reward_to_pay', models.FloatField(null=True, verbose_name='Valor máximo pago pela Banca')),
                ('min_bet_value', models.FloatField(null=True, verbose_name='Valor mínimo da aposta')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
