# Generated by Django 2.1.3 on 2019-03-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190314_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store',
        ),
    ]
