# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171212_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='punter',
            name='cellphone',
            field=models.CharField(default='0', max_length=14),
        ),
    ]
