# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_punter_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punter',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='punter',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='mobile_phone',
        ),
    ]
