# Generated by Django 2.1.3 on 2018-11-07 11:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Crédito'),
        ),
    ]
