# Generated by Django 2.0.1 on 2018-01-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_generalconfigurations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalconfigurations',
            options={'verbose_name': 'Configurar Restrições', 'verbose_name_plural': 'Configurar Restrições'},
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='min_number_of_choices_per_bet',
            field=models.IntegerField(default=1, verbose_name='Número mínimo de escolhas por Aposta'),
        ),
    ]
