# Generated by Django 2.0.1 on 2018-01-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180124_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_cotation_value',
            field=models.FloatField(default=200, verbose_name='Valor Máximo das Cotas'),
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='max_reward_to_pay',
            field=models.FloatField(default=50000, verbose_name='Valor máximo pago pela Banca'),
        ),
        migrations.AlterField(
            model_name='generalconfigurations',
            name='min_bet_value',
            field=models.FloatField(default=1, verbose_name='Valor mínimo da aposta'),
        ),
    ]
