# Generated by Django 2.0.1 on 2018-02-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180124_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'permissions': (('seller.be_seller', 'Be a seller permission'),), 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
