# Generated by Django 2.1.3 on 2018-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_manager_based_on_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='based_on_profit',
            field=models.BooleanField(default=False, verbose_name='Calcular comissão baseado no líquido ?'),
        ),
    ]
