# Generated by Django 2.1.3 on 2019-02-06 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181218_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='limit_time_to_cancel',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Tempo Limite de Cancelamento'),
        ),
    ]
