# Generated by Django 2.1.7 on 2019-04-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190412_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
    ]
