# Generated by Django 2.1.3 on 2019-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190206_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='can_change_limit_time',
            field=models.BooleanField(default=False, verbose_name='Pode Tempo de Cancelamento do Cambista?'),
        ),
    ]
