# Generated by Django 2.1.7 on 2019-04-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190404_1623'),
        ('user', '0008_auto_20190412_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='my_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
    ]
