# Generated by Django 2.1.7 on 2019-05-02 17:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_admin_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBO',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.seller',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
