# Generated by Django 2.1.7 on 2019-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sellerbo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerBO',
        ),
    ]
