# Generated by Django 2.0.1 on 2018-03-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('core', '0017_auto_20180225_2039'),
        ('user', '0009_auto_20180302_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='seller_ptr',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
