# Generated by Django 2.1.7 on 2019-05-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190506_1521'),
        ('ticket', '0006_auto_20190502_1517'),
        ('user', '0010_delete_sellerbo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalUser',
            new_name='AnonymousUser',
        ),
    ]
