# Generated by Django 2.1.3 on 2019-02-06 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190206_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='limit_time_to_cancel',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='Tempo Limite de Cancelamento'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='limit_time_to_cancel',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='Tempo Limite de Cancelamento'),
        ),
    ]
