# Generated by Django 2.0.1 on 2018-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punter',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='cellphone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cellphone',
            field=models.CharField(default=999999, max_length=14, verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
