# Generated by Django 2.0.1 on 2018-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180310_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfigurations',
            name='percentual_reduction',
            field=models.IntegerField(default=100, verbose_name='Redução Percentual'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='credit_limit_to_add',
            field=models.FloatField(default=0, verbose_name='Crédito'),
        ),
    ]
