# Generated by Django 2.2.1 on 2019-05-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190513_1634'),
        ('user', '0012_auto_20190513_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnonymousUser',
            new_name='TicketOwner',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='based_on_profit',
            new_name='comission_based_on_profit',
        ),
    ]
