# Generated by Django 2.1.7 on 2019-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190516_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='punter',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='cellphone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cellphone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular'),
        ),
    ]
