# Generated by Django 2.0.1 on 2018-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180426_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='credit_limit',
            field=models.FloatField(default=0, verbose_name='Créditos'),
        ),
    ]
