# Generated by Django 2.1.7 on 2019-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190517_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Anonímo'), (1, 'Apostador'), (2, 'Vendedor'), (3, 'Gerente'), (4, 'Dono da Banca')], default=0, verbose_name='Tipo do Usuário'),
        ),
    ]
