# Generated by Django 2.0.5 on 2018-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180510_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Comissão'),
        ),
    ]
