# Generated by Django 2.0.5 on 2018-05-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180529_1028'),
        ('user', '0015_auto_20180510_2104'),
    ]

    operations = [
    ]
