# Generated by Django 2.1.7 on 2019-05-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190517_1620'),
        ('user', '0015_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='my_store',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='my_store',
        ),
        migrations.RemoveField(
            model_name='punter',
            name='my_store',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='my_store',
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
    ]
