# Generated by Django 2.0.5 on 2018-05-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180529_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='can_sell_ilimited',
            new_name='can_sell_unlimited',
        ),
    ]
