# Generated by Django 2.0.5 on 2018-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_seller_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Comissão'),
        ),
    ]
