# Generated by Django 2.2.2 on 2019-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_manager_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profit_comission',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=30, verbose_name='Comissão do lucro'),
        ),
    ]
