# Generated by Django 2.0.5 on 2018-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180531_1229'),
        ('user', '0017_manager_commission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RandomUser',
            new_name='NormalUser',
        ),
    ]
