# Generated by Django 2.2.2 on 2019-06-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_manager_profit_comission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='profit_comission',
        ),
    ]
