# Generated by Django 2.0.5 on 2018-06-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180531_1229'),
        ('user', '0017_auto_20180529_1734'),
    ]

    operations = [
    ]
