# Generated by Django 2.0.5 on 2018-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20180608_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='can_sell_unlimited',
            field=models.BooleanField(default=True, verbose_name='Vender Ilimitado?'),
        ),
    ]
