# Generated by Django 2.0.5 on 2018-06-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20180608_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerManagerAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_made_assoc', models.CharField(max_length=80)),
                ('assoc_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Associação')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assoc', to='user.Manager', verbose_name='Gerente')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_assoc', to='user.Seller', verbose_name='Vendedor')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralConfigurations',
        ),
    ]
