# Generated by Django 2.0.5 on 2018-06-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20180608_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellermanagerassoc',
            options={'verbose_name': 'Gerente e Vendedor', 'verbose_name_plural': 'Gerentes e Vendedores'},
        ),
        migrations.AlterField(
            model_name='sellermanagerassoc',
            name='who_made_assoc',
            field=models.CharField(max_length=80, verbose_name='Quem associou?'),
        ),
    ]
