# Generated by Django 2.0.5 on 2018-06-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20180608_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellermanagerassoc',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='sellermanagerassoc',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='my_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assoc', to='user.Manager', verbose_name='Gerente'),
        ),
        migrations.DeleteModel(
            name='SellerManagerAssoc',
        ),
    ]
