# Generated by Django 2.2.3 on 2019-07-05 17:39

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190705_1724'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='punter',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seller',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
