# Generated by Django 2.0.5 on 2018-06-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20180608_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='my_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assoc', to='user.Manager', verbose_name='Gerente'),
        ),
    ]
