# Generated by Django 2.0.6 on 2018-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20180609_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='can_sell_unlimited',
            field=models.BooleanField(default=False, verbose_name='Vender Ilimitado?'),
        ),
    ]
