# Generated by Django 2.2.3 on 2019-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190715_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Anonímo'), (1, 'Apostador'), (2, 'Cambista'), (3, 'Gerente'), (4, 'Dono da Banca')], default=0, verbose_name='Tipo do Usuário'),
        ),
    ]
