# Generated by Django 2.0.6 on 2018-06-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20180614_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punter',
            options={'permissions': (('be_punter', 'Be a punter, permission.'),), 'verbose_name': 'Apostador', 'verbose_name_plural': 'Apostadores'},
        ),
    ]
