# Generated by Django 2.0.6 on 2018-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_manager_can_cancel_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='can_cancel_ticket',
            field=models.BooleanField(default=True, verbose_name='Cancela Ticket ?'),
        ),
    ]
