# Generated by Django 2.2.3 on 2019-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20190717_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='can_modify_seller',
            field=models.BooleanField(default=False, verbose_name='Pode alterar ou deletar Cambista?'),
        ),
    ]
