# Generated by Django 2.2.3 on 2019-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_manager_can_modify_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='can_modify_seller_comissions',
            field=models.BooleanField(default=False, verbose_name='Pode alterar comissões de Cambista?'),
        ),
    ]
