# Generated by Django 2.0.6 on 2018-06-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20180618_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('-pk',), 'permissions': (('be_manager', 'Be a manager, permission.'),), 'verbose_name': 'Gerente', 'verbose_name_plural': 'Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('-pk',), 'permissions': (('be_seller', 'Be a seller, permission.'),), 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
