# Generated by Django 2.2.4 on 2019-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_manager_can_modify_seller_comissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='cpf',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cpf',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='CPF'),
        ),
    ]
