# Generated by Django 2.0.6 on 2018-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20180705_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='can_sell_unlimited',
            field=models.BooleanField(default=False, verbose_name='Vender Ilimitado?'),
        ),
    ]
