# Generated by Django 2.2.6 on 2019-10-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20190819_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='can_close_cashier',
            field=models.BooleanField(default=False, verbose_name='Pode fechar o caixa ?'),
        ),
    ]
