# Generated by Django 2.1.3 on 2019-03-13 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20190313_1741'),
        ('core', '0002_auto_20190313_1741'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller', verbose_name='Cambista'),
        ),
        migrations.AddField(
            model_name='reward',
            name='who_rewarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='normal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.NormalUser', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Cambista'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Apostador'),
        ),
    ]
