# Generated by Django 2.1.7 on 2019-03-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190313_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-pk',), 'permissions': (('can_validate_payment', 'Can validate user ticket'), ('can_reward', 'Can reward a user')), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
