# Generated by Django 2.2 on 2019-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190323_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='who_set_payment',
            new_name='who_paid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Resultados'), (1, 'Não Venceu'), (2, 'Venceu'), (3, 'Venceu, Vencedor não Pago'), (4, 'Venceu, Vencedor Pago'), (5, 'Cancelado')], default=0, verbose_name='Status do Ticket'),
        ),
    ]
