# Generated by Django 2.2 on 2019-05-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190501_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status_payment',
            new_name='status',
        ),
    ]
