# Generated by Django 2.2 on 2019-05-02 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190501_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='who_rewarded',
            new_name='who_rewarded_the_winner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manager_was_rewarded',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='seller_was_rewarded',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_status',
        ),
        migrations.AddField(
            model_name='reward',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento do Prêmio'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Pagamento'), (1, 'Pagamento em Análise'), (2, 'Pago'), (3, 'Pagamento Cancelado'), (4, 'Pagamento Recusado pelo Cartão'), (5, 'Pagamento Reembolsado')], default=0, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Reward', verbose_name='Prêmio'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Resultados'), (1, 'Não Venceu'), (2, 'Venceu'), (3, 'Venceu, Bilhete não Pago'), (4, 'Venceu, Prestar Contas'), (5, 'Cancelado'), (6, 'Reebolsado')], default=0, verbose_name='Status do Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Apostador'),
        ),
    ]
