# Generated by Django 2.2.1 on 2019-05-16 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_auto_20190516_1630'),
        ('ticket', '0006_auto_20190502_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='normal_user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator_type',
            field=models.IntegerField(choices=[(0, 'Anonímo'), (1, 'Apostador'), (2, 'Vendedor'), (3, 'Dono da Banca')], default=0, verbose_name='Tipo do Usuário'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.TicketOwner', verbose_name='Dono do Bilhete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Payment', verbose_name='Pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reward',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Reward', verbose_name='Prêmio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to='core.Store', verbose_name='Banca'),
        ),
    ]
