# Generated by Django 2.2.1 on 2019-05-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190516_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='value',
            new_name='bet_value',
        ),
        migrations.AddField(
            model_name='payment',
            name='who_paid_type',
            field=models.IntegerField(choices=[(0, 'Vendedor'), (1, 'Dono da Banca')], default=0, verbose_name='Tipo de Usuário que Pagou'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='who_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambista'),
        ),
    ]
