# Generated by Django 2.1.7 on 2019-05-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190516_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator_type',
        ),
    ]
