# Generated by Django 2.2.1 on 2019-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20190517_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='visible',
        ),
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponível?'),
        ),
    ]
