# Generated by Django 2.2.2 on 2019-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20190517_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='AAAA-1111', max_length=10, verbose_name='Ticket ID'),
            preserve_default=False,
        ),
    ]
