# Generated by Django 2.2.2 on 2019-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30, verbose_name='Valor da Recompensa'),
            preserve_default=False,
        ),
    ]
