# Generated by Django 2.2.2 on 2019-06-17 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20190611_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_for_manager',
            field=models.BooleanField(default=False, verbose_name='Prestou conta com o gerente?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_for_seller',
            field=models.BooleanField(default=False, verbose_name='Prestou conta com o vendedor?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cotations',
            field=models.ManyToManyField(related_name='ticket', to='core.Cotation', verbose_name='Cotas'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 15, 43, 42), verbose_name='Data da Aposta'),
        ),
    ]
