# Generated by Django 2.2.2 on 2019-06-21 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20190617_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 16, 9, 7), verbose_name='Data da Aposta'),
        ),
    ]
