# Generated by Django 2.2.2 on 2019-06-21 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_auto_20190621_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 17, 26, 29), verbose_name='Data da Aposta'),
        ),
    ]
