# Generated by Django 2.2.2 on 2019-06-24 17:59

from django.db import migrations, models
import utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_auto_20190621_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(default=utils.timezone.now, verbose_name='Data da Aposta'),
        ),
    ]
