# Generated by Django 2.2.3 on 2019-07-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20190710_1453'),
        ('ticket', '0024_auto_20190710_1511'),
    ]

    operations = [
    ]
