# Generated by Django 2.2.4 on 2019-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_merge_20190710_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed_for_manager',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_for_seller',
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_in_for_manager',
            field=models.BooleanField(default=False, verbose_name='Entrada Gerente Caixa'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_in_for_seller',
            field=models.BooleanField(default=False, verbose_name='Entrada Vendedor Caixa'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_out_for_manager',
            field=models.BooleanField(default=False, verbose_name='Saída Gerente Caixa'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_out_for_seller',
            field=models.BooleanField(default=False, verbose_name='Saída Vendedor Caixa'),
        ),
    ]
