# Generated by Django 2.2.4 on 2019-08-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_auto_20190820_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor da Recompensa'),
        ),
    ]
