# Generated by Django 2.2.4 on 2019-09-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_auto_20190829_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
    ]
