COUNTRIES = {
"global":"Global",
"ae":"Emirados Árabes Unidos",
"gg":"Guernsey",
"rs":"Sérvia",
"ax":"Ilhas de Aland",
"bl":"Saint Barthélemy",
"bq":"Países Baixos Caribenhos",
"sx":"São Martinho",
"im":"Ilha of Man",
"md":"Moldávia",
"mf":"Saint Martin",
"je":"Jersey",
"ug":"Uganda",
"gb":"Inglaterra",
"um":"Ilhas Menores Distantes dos EUA",
"us":"Estados Unidos",
"uz":"Uzbequistão",
"va":"Santa Sé (Estado da Cidade do Vaticano)",
"vc":"São Vicente e Granadinas",
"vg":"Ilhas Virgens Britânicas",
"vn":"Vietnã",
"vu":"Vanuatu",
"wf":"Ilhas Wallis e Futuna",
"yt":"Mayotte",
"za":"África do Sul",
"zw":"Zimbábue",
"om":"Omã",
"pe":"Peru",
"pf":"Polinésia (francês)",
"pg":"Papua Nova Guiné",
"pk":"Paquistão",
"pl":"Polônia",
"pm":"São Pedro e Miquelon",
"pn":"Ilha Pitcairn",
"pr":"Porto Rico",
"rw":"Ruanda",
"sj":"Ilhas Svalbard e Jan Mayen",
"sn":"Senegal",
"tc":"Ilhas Turks e Caicos",
"th":"Tailândia",
"tv":"Tuvalu",
"mt":"Malta",
"ni":"Nicarágua",
"nr":"Nauru",
"lv":"Letônia",
"dm":"Dominica",
"et":"Etiópia",
"fm":"Micronésia",
"gd":"Granada",
"ge":"Geórgia",
"gf":"Guiana Francesa",
"gi":"Gibraltar",
"gm":"Gâmbia",
"gp":"Guadalupe (francês)",
"gq":"Guiné Equatorial",
"gr":"Grécia",
"gs":"S. Georgia & S. Sandwich Isls.",
"gt":"Guatemala",
"gu":"Guam (USA)",
"52":"Guiana",
"hk":"Hong Kong",
"hm":"Heard and McDonald Islands",
"hr":"Croácia",
"ht":"Haiti",
"hu":"Hungria",
"id":"Indonésia",
"ie":"Irlanda",
"il":"Israel",
"in":"Índia",
"io":"Território Britânico do Oceano Índico",
"jm":"Jamaica",
"jo":"Jordânia",
"kh":"Reino de Camboja",
"kp":"Coreia do Norte",
"li":"Liechtenstein",
"af":"Afeganistão",
"am":"Armênia",
"aw":"Aruba",
"bo":"Bolívia",
"bv":"Ilha Bouvet",
"ca":"Canadá",
"cm":"Camarões",
"cy":"Chipre",
"pt":"Portugal",
"pw":"Palau",
"ro":"Romênia",
"ru":"Rússia",
"sa":"Arábia Saudita",
"sb":"Ilhas Salomão",
"sc":"Seychelles",
"se":"Suécia",
"sh":"Santa Helena",
"si":"Eslovênia",
"sk":"Eslováquia",
"sl":"Serra Leoa",
"sm":"San Marino",
"so":"Somália",
"sr":"Suriname",
"st":"São Tomé e Príncipe",
"sv":"El Salvador",
"sy":"Síria",
"sz":"Suazilândia",
"td":"Chade",
"tf":"Territórios Franceses do Sul",
"tg":"Togo",
"tj":"Tajiquistão",
"tk":"Tokelau",
"tm":"Turcomenistão",
"tn":"Tunísia",
"tl":"Timor Leste",
"tr":"Turquia",
"tw":"Taiwan",
"mh":"Ilhas Marshall",
"ml":"Mali",
"mm":"Myanmar",
"mn":"Mongólia",
"mo":"Macau",
"mq":"Martinica (francês)",
"mr":"Mauritânia",
"ms":"Montserrat",
"mu":"Maurícia",
"mv":"Maldivas",
"mw":"Malaui",
"my":"Malásia",
"mz":"Moçambique",
"na":"Namíbia",
"ne":"Níger",
"nf":"Ilha Norfolk",
"ng":"Nigéria",
"nl":"Holanda",
"no":"Noruega",
"np":"Nepal",
"nu":"Niue",
"nz":"Nova Zelândia",
"ls":"Lesotho",
"lt":"Lituânia",
"lu":"Luxemburgo",
"ly":"Líbia",
"ma":"Marrocos",
"mc":"Mônaco",
"mg":"Madagáscar",
"dj":"Djibouti",
"dk":"Dinamarca",
"do":"República Dominicana",
"dz":"Argélia",
"ec":"Equador",
"ee":"Estônia",
"eh":"Saara Ocidental",
"er":"Eritréia",
"es":"Espanha",
"fi":"Finlândia",
"fj":"Fiji",
"fk":"Ilhas Falkland",
"fo":"ilhas Faroe",
"fr":"França",
"jp":"Japão",
"ke":"Quênia",
"kg":"Quirguizistão (Quirguistão)",
"ki":"Kiribati",
"km":"Comores",
"kn":"São Cristóvão e Nevis Anguilla",
"kr":"Coreia do Sul",
"kw":"Kuwait",
"ky":"Ilhas Cayman",
"la":"Laos",
"lb":"Líbano",
"lc":"Santa Lúcia",
"lk":"Sri Lanka",
"de":"Alemanha",
"ag":"Antígua e Barbuda",
"ai":"Anguilla",
"al":"Albânia",
"ao":"Angola",
"aq":"Antártica",
"ws":"Samoa Americana",
"at":"Áustria",
"au":"Austrália",
"az":"Azerbaijão",
"ba":"Bósnia-Herz",
"bb":"Barbados",
"be":"Bélgica",
"bf":"Burkina Faso",
"bg":"Bulgária",
"bh":"Bahrain",
"bj":"Benin",
"bm":"Bermudas",
"bn":"Brunei Darussalam",
"br":"Brasil",
"bs":"Bahamas",
"bt":"Butão",
"bw":"Botsuana",
"by":"Bielorrússia",
"bz":"Belize",
"cc":"Ilhas Cocos (Keeling)",
"cf":"República Centro-Africana",
"cd":"RD do Congo",
"ch":"Suíça",
"ci":"Costa do Marfim",
"ck":"Ilhas Cook",
"cl":"Chile",
"cn":"China",
"co":"Colômbia",
"cr":"Costa Rica",
"cu":"Cuba",
"cv":"Cabo Verde",
"cx":"Ilha do Natal",
"cz":"República Checa",
"ar":"Argentina",
"bd":"Bangladesh",
"bi":"Burundi",
"cg":"Congo",
"eg":"Egito",
"ga":"Gabão",
"gh":"Gana",
"gl":"Gronelândia",
"gn":"Guiné",
"hn":"Honduras",
"is":"Islândia",
"iq":"Iraque",
"it":"Itália",
"kz":"Cazaquistão",
"lr":"Libéria",
"mx":"México",
"mp":"Ilhas Marianas do Norte",
"pa":"Panamá",
"py":"Paraguai",
"ph":"Filipinas",
"qa":"Catar",
"as":"Samoa",
"sg":"Cingapura",
"sd":"Sudão",
"ss":"Sudão do Sul",
"to":"Tonga",
"tt":"Trinidad e Tobago",
"ua":"Ucrânia",
"uy":"Uruguai",
"ve":"Venezuela",
"ye":"Iémen",
"zm":"Zâmbia",
"mk":"Macedônia",
"vi":"Ilhas Virgens (EUA)",
"tz":"Tanzânia",
"gw":"Guiné Bissau",
"ir":"Irã",
"re":"Reunião",
"ps":"Palestina",
"me":"Montenegro",
"ad":"Andorra",
"gy":"Guiana Francesa",
"nc":"Nova Caledônia",
"cw":"Curaçao"
}