# Generated by Django 2.0.5 on 2018-05-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0018_auto_20180531_1229'),
        ('core', '0023_betticket_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('transferred_amount', models.FloatField(verbose_name='Valor Transferido')),
                ('seller_before_balance', models.FloatField(null=True, verbose_name='Saldo Anterior')),
                ('seller_after_balance', models.FloatField(null=True, verbose_name='Saldo Atual')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Manager', verbose_name='Gerente')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Transação - Gerente',
                'verbose_name_plural': 'Transações - Gerentes',
            },
        ),
        migrations.CreateModel(
            name='RevenueHistoryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_reseted_revenue', models.CharField(max_length=200, verbose_name='Reponsável pelo Fechamento')),
                ('revenue_reseted_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('final_revenue', models.FloatField(null=True, verbose_name='Faturamento')),
                ('actual_comission', models.FloatField(null=True, verbose_name='Comissão')),
                ('earned_value', models.FloatField(null=True, verbose_name='Valor Recebido')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Manager', verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Pagamentos - Gerente',
                'verbose_name_plural': 'Pagamentos - Gerentes',
            },
        ),
        migrations.CreateModel(
            name='RevenueHistorySeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_reseted_revenue', models.CharField(max_length=200, verbose_name='Reponsável pelo Fechamento')),
                ('revenue_reseted_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('final_revenue', models.FloatField(null=True, verbose_name='Faturamento')),
                ('actual_comission', models.FloatField(null=True, verbose_name='Comissão')),
                ('earned_value', models.FloatField(null=True, verbose_name='Valor Recebido')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pagamentos - Vendedor',
                'verbose_name_plural': 'Pagamentos - Vendedores',
            },
        ),
        migrations.CreateModel(
            name='SellerSalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('value', models.FloatField(verbose_name='Valor Apostado')),
                ('seller_before_balance', models.FloatField(null=True, verbose_name='Saldo Anterior')),
                ('seller_after_balance', models.FloatField(null=True, verbose_name='Saldo Anterior')),
                ('bet_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BetTicket', verbose_name='Ticket Criado')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Histórico - Vendedor',
                'verbose_name_plural': 'Histórico - Vendedores',
            },
        ),
    ]
