# Generated by Django 2.0.5 on 2018-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellersaleshistory',
            options={'verbose_name': 'Transação - Vendedor', 'verbose_name_plural': 'Transações - Vendedores'},
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='seller_after_balance',
            field=models.FloatField(null=True, verbose_name='Saldo Atual'),
        ),
    ]
