# Generated by Django 2.2.1 on 2019-05-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190516_1630'),
        ('history', '0002_auto_20190313_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcancelationhistory',
            options={'verbose_name': 'Cancelamento de Bilhete', 'verbose_name_plural': 'Cancelamento de Bilhetes'},
        ),
        migrations.RemoveField(
            model_name='ticketcancelationhistory',
            name='seller_of_payed',
        ),
        migrations.AddField(
            model_name='ticketcancelationhistory',
            name='who_paid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Quem Pagou o Ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketcancelationhistory',
            name='cancelation_date',
            field=models.DateTimeField(verbose_name='Data do Cancelamento'),
        ),
    ]
