# Generated by Django 2.0.5 on 2018-06-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20180608_1610'),
        ('core', '0025_merge_20180608_1327'),
        ('history', '0002_auto_20180608_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunterPayedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punter_payed', models.CharField(max_length=200, verbose_name='Apostador')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('payed_value', models.FloatField(verbose_name='Valor Pago')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Vendedor')),
                ('ticket_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BetTicket', verbose_name='Ticket Vencedor')),
            ],
            options={
                'verbose_name': 'Pagamento - Apostador',
                'verbose_name_plural': 'Pagamentos - Apostadores',
            },
        ),
    ]
