# Generated by Django 2.0.6 on 2018-06-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_punterpayedhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managertransactions',
            old_name='seller_after_balance',
            new_name='manager_after_balance',
        ),
        migrations.RenameField(
            model_name='managertransactions',
            old_name='seller_before_balance',
            new_name='manager_before_balance',
        ),
    ]
