# Generated by Django 2.1.3 on 2018-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20181105_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuehistoryseller',
            name='actual_comission',
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='actual_comission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='% Comissão'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='earned_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='final_out_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Saída Total'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='final_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Entrada Total'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='earned_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='final_out_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Saída Total'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='final_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Entrada Total'),
        ),
    ]
