# Generated by Django 2.2.1 on 2019-05-17 15:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190517_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0010_auto_20190517_1502'),
        ('history', '0004_auto_20190516_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerPaymentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=200, verbose_name='Nome do Apostador')),
                ('date', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('bet_value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Pago')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Banca')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='Bilhete Vencedor')),
                ('who_rewarded_the_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_payed_winner_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Cambista')),
            ],
            options={
                'verbose_name': 'Pag. - Apostador',
                'verbose_name_plural': 'Pag. - Apostadores',
            },
        ),
        migrations.RenameField(
            model_name='ticketcancelationhistory',
            old_name='cancelation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ticketcancelationhistory',
            old_name='ticket_cancelled',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketvalidationhistory',
            name='validation_date',
        ),
        migrations.AddField(
            model_name='ticketvalidationhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 15, 2, 55, 963994), verbose_name='Data da Validação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketcancelationhistory',
            name='who_cancelled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_canceled_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Quem Cancelou ?'),
        ),
        migrations.AlterField(
            model_name='ticketcancelationhistory',
            name='who_paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_canceled_tickets_who_i_paid', to=settings.AUTH_USER_MODEL, verbose_name='Quem Pagou o Ticket Cancelado'),
        ),
        migrations.AlterField(
            model_name='ticketvalidationhistory',
            name='who_validated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ticket_validations', to=settings.AUTH_USER_MODEL, verbose_name='Quem Validou'),
        ),
        migrations.DeleteModel(
            name='PunterPayedHistory',
        ),
    ]
