# Generated by Django 2.0.6 on 2018-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20180611_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertransactions',
            name='seller_after_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Atual(Vendedor)'),
        ),
        migrations.AddField(
            model_name='managertransactions',
            name='seller_before_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Anterior(Vendedor)'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='manager_after_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='manager_before_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='seller_after_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='seller_before_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo Anterior'),
        ),
    ]
