# Generated by Django 2.0.6 on 2018-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20180611_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='punterpayedhistory',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
