# Generated by Django 2.2.2 on 2019-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20190517_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketvalidationhistory',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Posterior'),
        ),
    ]
