# Generated by Django 2.2.2 on 2019-06-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20190625_1433'),
        ('history', '0006_auto_20190624_1706'),
    ]

    operations = [
    ]
