# Generated by Django 2.0.6 on 2018-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_punterpayedhistory_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertransactions',
            name='manager_after_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='manager_before_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='seller_after_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Atual(Vendedor)'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='seller_before_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Anterior(Vendedor)'),
        ),
        migrations.AlterField(
            model_name='managertransactions',
            name='transferred_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Transferido'),
        ),
        migrations.AlterField(
            model_name='punterpayedhistory',
            name='payed_value',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='actual_comission',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='earned_value',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='final_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Faturamento'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='actual_comission',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='earned_value',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='final_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, verbose_name='Faturamento'),
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='seller_after_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='seller_before_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='sellersaleshistory',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Apostado'),
        ),
    ]
