# Generated by Django 2.2.2 on 2019-06-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_merge_20190625_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0007_merge_20190625_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuehistorymanager',
            old_name='actual_comission',
            new_name='comission',
        ),
        migrations.RenameField(
            model_name='revenuehistorymanager',
            old_name='revenue_reseted_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='revenuehistorymanager',
            old_name='final_revenue',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='revenuehistorymanager',
            old_name='final_out_value',
            new_name='total_out',
        ),
        migrations.RemoveField(
            model_name='revenuehistorymanager',
            name='earned_value',
        ),
        migrations.RemoveField(
            model_name='revenuehistorymanager',
            name='who_reseted_revenue',
        ),
        migrations.AddField(
            model_name='revenuehistorymanager',
            name='register_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='quem prestou conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenuehistorymanager',
            name='tickets_registered',
            field=models.ManyToManyField(to='ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='revenuehistorymanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='user.Manager', verbose_name='Gerente'),
        ),
    ]
