# Generated by Django 2.0.6 on 2018-06-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20180614_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuehistorymanager',
            name='final_out_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Total Pago'),
        ),
        migrations.AddField(
            model_name='revenuehistorymanager',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='final_out_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True, verbose_name='Total Pago'),
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Lucro'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='final_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Total Faturado'),
        ),
    ]
