# Generated by Django 2.2.2 on 2019-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20190625_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuehistorymanager',
            name='out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='% Comissão'),
        ),
    ]
