# Generated by Django 2.0.6 on 2018-06-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_game_odds_calculated'),
        ('history', '0009_auto_20180614_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCancelationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_cancelled', models.CharField(max_length=200, verbose_name='Quem Cancelou ?')),
                ('cancelation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('ticket_cancelled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BetTicket', verbose_name='Ticket Cancelado')),
            ],
            options={
                'verbose_name': 'Cancelamento - Ticket',
                'verbose_name_plural': 'Cancelamentos - Tickets',
            },
        ),
    ]
