# Generated by Django 2.2.2 on 2019-06-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0023_merge_20190625_1502'),
        ('history', '0009_revenuehistorymanager_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuehistoryseller',
            old_name='revenue_reseted_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='revenuehistoryseller',
            old_name='final_revenue',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='revenuehistoryseller',
            old_name='final_out_value',
            new_name='total_out',
        ),
        migrations.RemoveField(
            model_name='revenuehistoryseller',
            name='earned_value',
        ),
        migrations.RemoveField(
            model_name='revenuehistoryseller',
            name='who_reseted_revenue',
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='comission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='% Comissão'),
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='% Comissão'),
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='register_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='quem prestou conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenuehistoryseller',
            name='tickets_registered',
            field=models.ManyToManyField(to='ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='revenuehistoryseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='user.Seller', verbose_name='Cambista'),
        ),
    ]
