# Generated by Django 2.2.2 on 2019-07-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20190626_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managertransactions',
            old_name='manager_after_balance',
            new_name='creditor_after_balance',
        ),
        migrations.RenameField(
            model_name='managertransactions',
            old_name='manager_before_balance',
            new_name='creditor_before_balance',
        ),
    ]
