# Generated by Django 2.0.6 on 2018-06-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20180618_2050'),
        ('history', '0010_ticketcancelationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcancelationhistory',
            name='seller_of_payed',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user.Seller', verbose_name='Vendedor'),
            preserve_default=False,
        ),
    ]
