# Generated by Django 2.0.6 on 2018-06-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_ticketcancelationhistory_seller_of_payed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managertransactions',
            options={'verbose_name': 'Transf. - Gerente', 'verbose_name_plural': 'Transf. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='punterpayedhistory',
            options={'verbose_name': 'Pag. - Apostador', 'verbose_name_plural': 'Pag. - Apostadores'},
        ),
        migrations.AlterModelOptions(
            name='revenuehistorymanager',
            options={'verbose_name': 'Pag. - Gerente', 'verbose_name_plural': 'Pag. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='revenuehistoryseller',
            options={'verbose_name': 'Pag. - Vendedor', 'verbose_name_plural': 'Pag. - Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='sellersaleshistory',
            options={'verbose_name': 'Entrada - Vendedor', 'verbose_name_plural': 'Entradas - Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='ticketcancelationhistory',
            options={'verbose_name': 'Can. - Ticket', 'verbose_name_plural': 'Can. - Tickets'},
        ),
    ]
