# Generated by Django 2.2.2 on 2019-07-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0012_auto_20190701_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managertransactions',
            name='seller',
        ),
        migrations.AddField(
            model_name='managertransactions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cambista'),
            preserve_default=False,
        ),
    ]
