# Generated by Django 2.2.2 on 2019-07-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0013_auto_20190703_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managertransactions',
            old_name='seller_after_balance',
            new_name='user_after_balance',
        ),
        migrations.RenameField(
            model_name='managertransactions',
            old_name='seller_before_balance',
            new_name='user_before_balance',
        ),
    ]
