# Generated by Django 2.2.3 on 2019-07-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0014_auto_20190703_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcancelationhistory',
            options={'ordering': ('-pk',), 'verbose_name': 'Cancelamento de Bilhete', 'verbose_name_plural': 'Cancelamento de Bilhetes'},
        ),
    ]
