# Generated by Django 2.2.3 on 2019-07-25 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0032_auto_20190717_1809'),
        ('core', '0045_auto_20190717_1135'),
        ('ticket', '0025_merge_20190710_1622'),
        ('history', '0015_auto_20190717_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevenueHistoryManager',
            new_name='ManagerCashierHistory',
        ),
        migrations.AlterModelOptions(
            name='managercashierhistory',
            options={'ordering': ('-pk',), 'verbose_name': 'Pag. - Gerente', 'verbose_name_plural': 'Pag. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='managertransactions',
            options={'ordering': ('-pk',), 'verbose_name': 'Transf. - Gerente', 'verbose_name_plural': 'Transf. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='revenuehistoryseller',
            options={'ordering': ('-pk',), 'verbose_name': 'Pag. - Cambista', 'verbose_name_plural': 'Pag. - Cambistas'},
        ),
        migrations.AlterModelOptions(
            name='ticketvalidationhistory',
            options={'ordering': ('-pk',), 'verbose_name': 'Validação de Aposta', 'verbose_name_plural': 'Validações de Apostas'},
        ),
        migrations.AlterModelOptions(
            name='winnerpaymenthistory',
            options={'ordering': ('-pk',), 'verbose_name': 'Pag. - Apostador', 'verbose_name_plural': 'Pag. - Apostadores'},
        ),
    ]
