# Generated by Django 2.2.3 on 2019-07-25 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0032_auto_20190717_1809'),
        ('ticket', '0025_merge_20190710_1622'),
        ('core', '0045_auto_20190717_1135'),
        ('history', '0016_auto_20190725_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevenueHistorySeller',
            new_name='SellerCashierHistory',
        ),
    ]
