# Generated by Django 2.2.3 on 2019-07-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_auto_20190725_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managercashierhistory',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers_history', to='user.Manager', verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='sellercashierhistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers_history', to='user.Seller', verbose_name='Cambista'),
        ),
    ]
