# Generated by Django 2.2.3 on 2019-07-29 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190726_1220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0018_auto_20190726_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerTransactions',
            new_name='CreditTransactions',
        ),
        migrations.DeleteModel(
            name='WinnerPaymentHistory',
        ),
    ]
