# Generated by Django 2.2.3 on 2019-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0019_auto_20190729_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercashierhistory',
            name='bonus_premio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Bônus por Prêmio'),
        ),
        migrations.AlterField(
            model_name='sellercashierhistory',
            name='out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Saída'),
        ),
    ]
