# Generated by Django 2.2.3 on 2019-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0020_auto_20190809_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercashierhistory',
            name='bonus_premio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Bônus por Prêmio'),
        ),
    ]
