# Generated by Django 2.2.4 on 2019-08-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0021_auto_20190809_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittransactions',
            options={'ordering': ('-id',), 'verbose_name': 'Transf. - Gerente', 'verbose_name_plural': 'Transf. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='managercashierhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Pag. - Gerente', 'verbose_name_plural': 'Pag. - Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='sellercashierhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Pag. - Cambista', 'verbose_name_plural': 'Pag. - Cambistas'},
        ),
        migrations.AlterModelOptions(
            name='ticketcancelationhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Cancelamento de Bilhete', 'verbose_name_plural': 'Cancelamento de Bilhetes'},
        ),
        migrations.AlterModelOptions(
            name='ticketvalidationhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Validação de Aposta', 'verbose_name_plural': 'Validações de Apostas'},
        ),
    ]
