# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 23:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bet_ticket_status', models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('Não Venceu', 'Não Venceu'), ('Venceu', 'Venceu')], default='Aguardando Resultados', max_length=80)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'permissions': (('can_validate_payment', 'Can validate user ticket'), ('can_reward', 'Can reward a user')),
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.FloatField(default=0)),
                ('winning', models.NullBooleanField()),
                ('is_standard', models.BooleanField(default=False)),
                ('kind', models.CharField(max_length=100)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cota',
                'verbose_name_plural': 'Cotas',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_game_date', models.DateTimeField()),
                ('status_game', models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Ao Vivo', 'Ao Vivo'), ('Meio Tempo', 'Meio Tempo'), ('Tempo Total', 'Tempo Total'), ('Tempo Extra', 'Tempo Extra'), ('Penaltis', 'Penaltis'), ('Terminou após tempo extra', 'Terminou após tempo extra'), ('Esperando tempo extra', 'Esperando tempo extra'), ('Tempo total após os penaltis', 'Tempo total após os penaltis'), ('Cancelado', 'Cancelado'), ('Adiado', 'Adiado'), ('Interrompindo', 'Interrompindo'), ('Abandonado', 'Abandonado'), ('Suspendido', 'Suspendido'), ('Premiado', 'Premiado'), ('Atrasado', 'Atrasado'), ('A ser anunciado', 'A ser anunciado'), ('WO', 'WO')], default='Não Iniciado', max_length=80)),
                ('odds_calculated', models.BooleanField()),
                ('visitor_team_score', models.IntegerField(blank=True, null=True)),
                ('local_team_score', models.IntegerField(blank=True, null=True)),
                ('ht_score', models.CharField(max_length=80, null=True)),
                ('ft_score', models.CharField(max_length=80, null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to='core.Championship')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_payment', models.CharField(choices=[('Aguardando Pagamento do Ticket', 'Aguardando Pagamento do Ticket'), ('Pago', 'Pago')], default='Aguardando Pagamento do Ticket', max_length=80)),
                ('payment_date', models.DateTimeField(auto_now=True, null=True)),
                ('who_set_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Seller')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status_reward', models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('O apostador foi pago', 'O apostador foi pago'), ('Esse ticket não venceu', 'Esse ticket não venceu'), ('Venceu, Aguardando pagamento', 'Venceu, Aguardando pagamento')], default='Aguardando Resultados', max_length=80)),
                ('who_rewarded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Seller')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.AddField(
            model_name='cotation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='core.Game'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cotations',
            field=models.ManyToManyField(related_name='bet_ticket', to='core.Cotation'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='reward',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Reward'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_tickets_validated_by_me', to='user.Seller'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bet_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
