# Generated by Django 2.0.1 on 2018-01-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='who_rewarded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.Seller'),
        ),
        migrations.AddField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.Seller'),
        ),
        migrations.AddField(
            model_name='game',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to='core.Championship'),
        ),
        migrations.AddField(
            model_name='cotation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='core.Game'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cotations',
            field=models.ManyToManyField(related_name='bet_ticket', to='core.Cotation'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Payment'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='normal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.NormalUser'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Reward'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_tickets_validated_by_me', to='user.Seller'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_bet_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
