# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='winning',
            field=models.BooleanField(),
        ),
    ]
