# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status_game',
            field=models.CharField(choices=[('NS', 'Não Iniciado'), ('LIVE', 'Ao Vivo'), ('HT', 'Meio Tempo'), ('FT', 'Tempo Total'), ('ET', 'Tempo Extra'), ('PEN_LIVE', 'Penaltis'), ('AET', 'Terminou após tempo extra'), ('BREAK', 'Esperando tempo extra'), ('FT_PEN', 'Tempo total após os penaltis'), ('CANCL', 'Cancelado'), ('POSTP', 'Adiado'), ('INT', 'Interrompindo'), ('ABAN', 'Abandonado'), ('SUSP', 'Suspendido'), ('AWARDED', 'Premiado'), ('DELAYED', 'Atrasado'), ('TBA', 'A ser anunciado'), ('WO', 'WO')], default='Não Iniciado', max_length=80),
        ),
    ]
