# Generated by Django 2.1.3 on 2019-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        ('utils', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations', to='core.Game', verbose_name='Jogo'),
        ),
        migrations.AddField(
            model_name='cotation',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations', to='core.Market', verbose_name='Tipo da Cota'),
        ),
        migrations.AddField(
            model_name='cotationhistory',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_history', to='core.Game', verbose_name='Jogo'),
        ),
        migrations.AddField(
            model_name='cotationhistory',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_history', to='core.Market', verbose_name='Tipo da Cota'),
        ),
        migrations.AddField(
            model_name='cotationhistory',
            name='original_cotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_cotation', to='core.Cotation', verbose_name='Cotação Original'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotationhistory',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotations_history', to='ticket.Ticket', verbose_name='Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.League', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.Location', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.Sport', verbose_name='Esporte'),
        ),
        migrations.AddField(
            model_name='league',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_leagues', to='core.Location', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='store',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.GeneralConfigurations', verbose_name='Configurações Gerais'),
        ),
    ]
