# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_bets', to='core.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betticket',
            name='bet_ticket_status',
            field=models.CharField(choices=[('WAITING_RESULT', 'waiting result'), ('NOT_WON', 'not won'), ('WON', 'won')], default=11, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betticket',
            name='punter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_bet_tickets', to='user.Punter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betticket',
            name='reward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Reward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bet_tickets_validated_by_me', to='user.Seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotation',
            name='bet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='core.Bet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotation',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='core.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotation',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('HAPPEN', 'happen'), ('NOT_HAPPEN', 'not_happen')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='championship',
            field=models.CharField(default=11, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'paid'), ('NOT_PAID', 'not_paid')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='who_rewarded',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='user.Seller'),
            preserve_default=False,
        ),
    ]
