# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_tickets_validated_by_me', to='user.Seller'),
        ),
    ]
