# Generated by Django 2.0.6 on 2018-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
