# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171112_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='status_payment',
        ),
        migrations.AddField(
            model_name='reward',
            name='status_reward',
            field=models.CharField(choices=[('DONE', 'done'), ('NONE', 'none')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
