# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180113_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='value',
            field=models.FloatField(),
        ),
    ]
