# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171107_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='name',
        ),
    ]
