# Generated by Django 2.0.6 on 2018-10-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_league_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
        migrations.AlterField(
            model_name='cotation',
            name='settlement',
            field=models.IntegerField(blank=True, choices=[(-1, 'Cancelada'), (1, 'Perdeu'), (2, 'Ganhou'), (3, 'Reembolso'), (4, 'Metade Perdida'), (5, 'Metade Ganha')], null=True),
        ),
    ]
