# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171128_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betticket',
            options={'permissions': (('can_validade_payment', 'Can validade user ticket'), ('can_reward', 'Can reward a user'))},
        ),
    ]
