# Generated by Django 2.0.6 on 2018-10-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cotation_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='games',
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_leagues', to='core.Sport'),
        ),
    ]
