# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171025_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start_game_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_date',
            field=models.DateTimeField(null=True),
        ),
    ]
