# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171108_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='status',
            field=models.CharField(choices=[('HOME', 'home'), ('TIE', 'tie'), ('AWAY', 'away')], max_length=25),
        ),
    ]
