# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_randomuser'),
        ('core', '0002_auto_20171228_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='random_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.RandomUser'),
        ),
    ]
