# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171105_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='visible',
        ),
        migrations.AddField(
            model_name='game',
            name='status_game',
            field=models.CharField(choices=[('FINISHED', 'finished'), ('HAPPENING', 'happening'), ('NOT_HAPPENING', 'not_happening')], default='not happening', max_length=45),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('HAPPENING', 'happening'), ('NOT_HAPPENING', 'not_happening')], max_length=25),
        ),
    ]
