# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171120_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Resultado em Aberto'), ('NOT_HAPPENED', 'Não aconteceu'), ('HAPPENED', 'Aconteceu')], default=('OPEN', 'Resultado em Aberto'), max_length=25),
        ),
    ]
