# Generated by Django 2.1.3 on 2019-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_update',
        ),
        migrations.AddField(
            model_name='game',
            name='can_be_modified_by_api',
            field=models.BooleanField(default=True, verbose_name='API pode modificar?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.IntegerField(choices=[(0, 'Não Iniciado'), (1, 'Ao Vivo'), (2, 'Para ser Concertado'), (3, 'Terminado'), (4, 'Adiado'), (5, 'Cancelado'), (6, 'W.O'), (7, 'Interrompido'), (8, 'Abandonado'), (9, 'Desistido'), (99, 'Removido')], verbose_name='Status do Jogo'),
        ),
    ]
