# Generated by Django 2.0.6 on 2018-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181015_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(help_text='Campeonato', max_length=120, verbose_name='Nome'),
        ),
    ]
