# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171108_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
        ),
    ]
