# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extracotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='name',
            field=models.CharField(choices=[('CASA', 'Casa'), ('EMPATE', 'Empate'), ('VISITANTE', 'Visitante')], max_length=30, null=True),
        ),
    ]
