# Generated by Django 2.0.6 on 2018-10-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181015_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date_update',
            new_name='last_update',
        ),
    ]
