# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171204_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='bet_ticket_status',
            field=models.CharField(choices=[('WAITING_RESULT', 'Aguardando Resultados.'), ('NOT_WON', 'Não Venceu.'), ('WON', 'Venceu.')], default='Aguardando Resultados.', max_length=45),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='status_game',
            field=models.CharField(choices=[('NS', 'Not Started'), ('LIVE', 'Live'), ('HT', 'Half-time'), ('FT', 'Full-Time'), ('ET', 'Extra-Time'), ('PEN_LIVE', 'Penalty Shootout'), ('AET', 'Finished after extra time'), ('BREAK', 'Match finished, waiting for extra time to start'), ('FT_PEN', 'Full-Time after penalties'), ('CANCL', 'Cancelled'), ('POSTP', 'PostPhoned'), ('INT', 'Interrupted'), ('ABAN', 'Abandoned'), ('SUSP', 'Suspended'), ('AWARDED', 'Awarded'), ('DELAYED', 'Delayed'), ('TBA', 'To Be Announced (Fixture will be updated with exact time later)'), ('WO', 'Walkover (Awarding of a victory to a contestant because there are no other contestants)')], default='Not Started', max_length=45),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_payment',
            field=models.CharField(choices=[('WATING_PAYMENT', 'Aguardando Pagamento do Ticket.'), ('PAID', 'Pago.')], default='Aguardando Pagamento do Ticket.', max_length=25),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status_reward',
            field=models.CharField(choices=[('WAITING_RESULTS', 'Aguardando Resultados.'), ('PAID', 'O apostador foi pago.'), ('NOT_WON', 'Esse ticket não venceu.')], default='Aguardando Resultados.', max_length=25),
        ),
    ]
