# Generated by Django 2.1.2 on 2018-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181022_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='reward_value',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_payment',
            field=models.CharField(choices=[('Aguardando Pagamento do Ticket', 'Aguardando Pagamento do Ticket'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Aguardando Pagamento do Ticket', max_length=80, verbose_name='Status do Pagamento'),
        ),
    ]
