# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171208_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betticket',
            options={'permissions': (('can_validate_payment', 'Can validate user ticket'), ('can_reward', 'Can reward a user')), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='cotation',
            options={'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Recompensa', 'verbose_name_plural': 'Recompensas'},
        ),
    ]
