# Generated by Django 2.1.3 on 2019-03-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190314_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
    ]
