# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171108_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='value_max',
            field=models.DecimalField(decimal_places=1, default=10000.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
