# Generated by Django 2.0.6 on 2018-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181015_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
