# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status_payment',
            field=models.CharField(choices=[('WATING_PAYMENT', 'Aguardando Pagamento do Ticket.'), ('PAID', 'Pago.')], default='Aguardando Pagamento do Ticket.', max_length=50),
        ),
    ]
