# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171210_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
    ]
