# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171107_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betticket',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='bet_ticket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.BetTicket'),
            preserve_default=False,
        ),
    ]
