# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171125_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='bet_ticket_status',
            field=models.CharField(choices=[('WAITING_RESULT', 'Aguardando Resultados'), ('NOT_WON', 'Não Ganhou'), ('WON', 'Ganhou')], default=('WAITING_RESULT', 'Aguardando Resultados'), max_length=45),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_payment',
            field=models.CharField(choices=[('PAID', 'Pago'), ('WATING_PAYMENT', 'Aguardando Pagamento do Ticket')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status_reward',
            field=models.CharField(choices=[('PAID', 'O apostador foi pago'), ('NOT_PAID', 'O apostador ainda não foi pago'), ('NOT_WON', 'Esse ticket não venceu')], max_length=25),
        ),
    ]
