# Generated by Django 2.1.3 on 2018-11-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cotation_id_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotationhistory',
            old_name='bet_ticket',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='cotationhistory',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='cotationhistory',
            name='settlement',
        ),
        migrations.RemoveField(
            model_name='cotationhistory',
            name='status',
        ),
    ]
