# Generated by Django 2.0.6 on 2018-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181015_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='settlement',
            field=models.IntegerField(choices=[(-1, 'Cancelada'), (1, 'Perdeu'), (2, 'Ganhou'), (3, 'Reembolso'), (4, 'Metade Perdida'), (3, 'Metade Ganha')], null=True),
        ),
    ]
