# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171212_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='punter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bet_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
