# Generated by Django 2.0.1 on 2018-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_betticket_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='seller_was_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
