# Generated by Django 2.1.7 on 2019-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_game_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cc',
            field=models.CharField(default='inter', max_length=5, unique=True, verbose_name='cc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
