# Generated by Django 2.0.1 on 2018-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reward_seller_was_rewarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='seller_was_rewarded',
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_was_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
