# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171206_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
