# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171212_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betticket',
            old_name='punter',
            new_name='user',
        ),
    ]
