# Generated by Django 2.1 on 2018-10-16 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '__first__'),
        ('core', '0007_auto_20181015_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BetTicket',
            new_name='Ticket',
        ),
    ]
