# Generated by Django 2.1 on 2018-10-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181016_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='status_game',
            new_name='game_status',
        ),
        migrations.RemoveField(
            model_name='league',
            name='location',
        ),
        migrations.RemoveField(
            model_name='league',
            name='sport',
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.Location', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.Sport', verbose_name='Esporte'),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.League', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
