# Generated by Django 2.1.7 on 2019-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190315_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.IntegerField(choices=[(1, 'Não Iniciado'), (2, 'Ao Vivo'), (3, 'Terminado'), (4, 'Cancelado'), (5, 'Adiado'), (6, 'Interrompindo'), (7, 'Abandonado'), (8, 'Pré-jogo'), (9, 'Quase Iniciado')], verbose_name='Status do Jogo'),
        ),
    ]
