# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171212_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='winning',
            field=models.NullBooleanField(),
        ),
    ]
