# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171206_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
