# Generated by Django 2.0.1 on 2018-01-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180121_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Data da aposta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_date',
            field=models.DateTimeField(null=True),
        ),
    ]
