# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171216_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='odds_calculated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
