# Generated by Django 2.1 on 2018-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181016_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='base_line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
