# Generated by Django 2.0.1 on 2018-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180125_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='odds_processed',
            field=models.BooleanField(default=False),
        ),
    ]
