# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_game_odds_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ft_score',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ht_score',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='local_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
