# Generated by Django 2.1.3 on 2018-11-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181105_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
        migrations.AddField(
            model_name='location',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
    ]
