# Generated by Django 2.1.7 on 2019-03-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_game_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cc',
        ),
    ]
