# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171217_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ft_score',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ht_score',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
