# Generated by Django 2.0.1 on 2018-02-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_game_odds_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='handicap',
        ),
    ]
