# Generated by Django 2.1.2 on 2018-10-16 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181016_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='seller_was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Cambista foi pago?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller', verbose_name='Cambista'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Cambista'),
        ),
    ]
