# Generated by Django 2.1.3 on 2018-11-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181106_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-id',), 'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
    ]
