# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171217_0620'),
        ('core', '0009_auto_20171216_1416'),
    ]

    operations = [
    ]
