# Generated by Django 2.1.3 on 2018-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181107_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='settlement',
            field=models.IntegerField(blank=True, choices=[(None, 'Em Aberto'), (-1, 'Cancelada'), (1, 'Perdeu'), (2, 'Ganhou'), (3, 'Reembolso'), (4, 'Metade Perdida'), (5, 'Metade Ganha')], null=True, verbose_name='Resultado'),
        ),
    ]
