# Generated by Django 2.1.7 on 2019-03-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_location_cc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-id'], 'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercados'},
        ),
    ]
