# Generated by Django 2.1.7 on 2019-03-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_location_cc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-id'], 'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercados'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('-pk',), 'verbose_name': 'Cópia Cotação', 'verbose_name_plural': 'Cópia Cotações'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('-pk',), 'verbose_name': 'Banca', 'verbose_name_plural': 'Bancas'},
        ),
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='customuser_ptr',
        ),
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='utils.GeneralConfigurations', verbose_name='Configurações Gerais'),
        ),
    ]
