# Generated by Django 2.1.3 on 2018-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181107_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização'),
        ),
    ]
