# Generated by Django 2.1.7 on 2019-03-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190321_1706'),
        ('core', '0013_auto_20190321_1309'),
    ]

    operations = [
    ]
