# Generated by Django 2.0.1 on 2018-02-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180206_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='local_team_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visitor_team_score',
        ),
    ]
