# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20171217_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='cotations',
            field=models.ManyToManyField(related_name='bet_ticket', to='core.Cotation'),
        ),
    ]
