# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171217_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='have_it',
            field=models.BooleanField(default=False),
        ),
    ]
