# Generated by Django 2.1.3 on 2018-11-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181107_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_visible',
            new_name='visible',
        ),
    ]
