# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_game_have_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='have_it',
        ),
    ]
