# Generated by Django 2.1.3 on 2018-11-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181107_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_visible',
            new_name='visible',
        ),
    ]
