# Generated by Django 2.1.7 on 2019-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190323_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em aberto'), (2, 'Suspensa'), (3, 'Finalizada')], verbose_name='Status da Cota'),
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mercado'),
        ),
    ]
