# Generated by Django 2.0.1 on 2018-02-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180225_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations', to='core.Market', verbose_name='Tipo da Cota'),
        ),
    ]
