# Generated by Django 2.1.7 on 2019-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190326_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='id_string',
        ),
        migrations.AlterField(
            model_name='cotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em aberto'), (2, 'Suspensa'), (3, 'Finalizada')], default=1, verbose_name='Status da Cota'),
        ),
    ]
