# Generated by Django 2.1.3 on 2018-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181107_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_status',
            field=models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('O apostador foi pago', 'O apostador foi pago'), ('Esse ticket não venceu', 'Esse ticket não venceu'), ('Venceu, Pagar Apostador', 'Venceu, Pagar Apostador'), ('Venceu, não pago', 'Venceu, não pago')], default='Aguardando Resultados', max_length=80, verbose_name='Status do Prêmio'),
        ),
    ]
