# Generated by Django 2.1.3 on 2018-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181108_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotationhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
