# Generated by Django 2.1.3 on 2018-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181111_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='settlement',
            field=models.IntegerField(blank=True, choices=[(None, 'Em Aberto'), (-1, 'Cancelada'), (1, 'Perdeu'), (2, 'Ganhou'), (3, 'Perdeu'), (4, 'Perdeu'), (5, 'Ganhou')], null=True, verbose_name='Resultado'),
        ),
    ]
