# Generated by Django 2.1.7 on 2019-03-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190326_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='base_line',
        ),
        migrations.RemoveField(
            model_name='cotation',
            name='line',
        ),
        migrations.AlterField(
            model_name='cotation',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última atualização'),
        ),
    ]
