# Generated by Django 2.1.7 on 2019-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190326_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
