# Generated by Django 2.1.3 on 2018-11-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181111_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
    ]
