# Generated by Django 2.0.5 on 2018-05-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cotationhistory_original_cotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterField(
            model_name='betticket',
            name='bet_ticket_status',
            field=models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('Não Venceu', 'Não Venceu'), ('Venceu', 'Venceu')], default='Aguardando Resultados', max_length=80, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Data da Aposta'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='country',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller_was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Já Prestou Contas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_payment',
            field=models.CharField(choices=[('Aguardando Pagamento do Ticket', 'Aguardando Pagamento do Ticket'), ('Pago', 'Pago')], default='Aguardando Pagamento do Ticket', max_length=80, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status_reward',
            field=models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('O apostador foi pago', 'O apostador foi pago'), ('Esse ticket não venceu', 'Esse ticket não venceu'), ('Venceu, Aguardando pagamento', 'Venceu, Aguardando pagamento')], default='Aguardando Resultados', max_length=80, verbose_name='Status do Prêmio'),
        ),
    ]
