# Generated by Django 2.0.5 on 2018-05-29 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180510_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_cotationhistory_original_cotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betticket',
            name='random_user',
        ),
        migrations.AddField(
            model_name='betticket',
            name='normal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='user.NormalUser', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
