# Generated by Django 2.0.5 on 2018-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180531_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betticket',
            old_name='random_user',
            new_name='normal_user',
        ),
    ]
