# Generated by Django 2.1.3 on 2018-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cotation_is_updating'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
