# Generated by Django 2.0.5 on 2018-05-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180529_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='normal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='user.NormalUser', verbose_name='Cliente'),
        ),
    ]
