# Generated by Django 2.1.3 on 2018-11-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_market_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercado'},
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mercado'),
        ),
    ]
