# Generated by Django 2.0.5 on 2018-05-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_auto_20180531_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
