# Generated by Django 2.1.7 on 2019-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190403_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_goals',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Total Acima/Abaixo'),
        ),
    ]
