# Generated by Django 2.0.5 on 2018-06-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180529_1028'),
        ('core', '0023_betticket_seller'),
    ]

    operations = [
    ]
