# Generated by Django 2.1.3 on 2018-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20181111_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponibilidade'),
        ),
    ]
