# Generated by Django 2.1.7 on 2019-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_game_total_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_goals',
        ),
        migrations.AddField(
            model_name='cotation',
            name='total_goals',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Total Acima/Abaixo'),
        ),
    ]
