# Generated by Django 2.1.3 on 2018-11-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181111_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercados'},
        ),
    ]
