# Generated by Django 2.0.5 on 2018-06-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20180608_1321'),
        ('core', '0024_merge_20180608_1214'),
    ]

    operations = [
    ]
