# Generated by Django 2.0.5 on 2018-06-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20180608_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ht_score',
            field=models.CharField(help_text='Placar meio-tempo Ex: 3-5 (Casa-Visita)', max_length=80, null=True, verbose_name='Placar até o meio-tempo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='odds_processed',
            field=models.BooleanField(default=False, verbose_name='Foi processado?'),
        ),
        migrations.RenameField(
            model_name='betticket',
            old_name='random_user',
            new_name='normal_user'
        )
   
    ]
