# Generated by Django 2.1.3 on 2018-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181112_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.IntegerField(choices=[(1, 'Não Iniciado'), (2, 'Ao Vivo'), (3, 'Terminado'), (4, 'Cancelado'), (5, 'Adiado'), (6, 'Interrompindo'), (7, 'Abandonado'), (8, 'Pré-jogo'), (9, 'Quase Iniciado')], verbose_name='Status do Jogo'),
        ),
    ]
