# Generated by Django 2.1.7 on 2019-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190403_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='total_goals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Acima/Abaixo'),
        ),
    ]
