# Generated by Django 2.0.5 on 2018-06-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180609_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='normal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.NormalUser', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Reward', verbose_name='Recompensa'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_bet_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Apostador'),
        ),
    ]
