# Generated by Django 2.1.7 on 2019-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190403_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.CharField(default='time', max_length=80, verbose_name='Time Fora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.CharField(default='time2', max_length=80, verbose_name='Time Casa'),
            preserve_default=False,
        ),
    ]
