# Generated by Django 2.1.7 on 2019-04-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190404_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotationModified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Modificado')),
                ('cotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifiy', to='core.Cotation', verbose_name='Cotas')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifiy', to='core.Store', verbose_name='Bancas')),
            ],
        ),
    ]
