# Generated by Django 2.1.3 on 2019-01-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181122_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='is_updating',
        ),
    ]
