# Generated by Django 2.1.7 on 2019-04-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cotationmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=100, verbose_name='Time Fora'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=100, verbose_name='Time Casa'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Jogo'),
        ),
    ]
