# Generated by Django 2.0.6 on 2018-06-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180611_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manager_was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Vendedor foi pago?'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='core.Payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='core.Reward', verbose_name='Recompensa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seller_was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Vendedor foi pago?'),
        ),
    ]
