# Generated by Django 2.0.6 on 2018-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180612_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='cotation_value_total',
            field=models.DecimalField(decimal_places=2, max_digits=99, verbose_name='Cota Total da Aposta'),
        ),
    ]
