# Generated by Django 2.2 on 2019-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190419_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='cotation',
            name='settlement',
            field=models.IntegerField(choices=[(0, 'Em Aberto'), (1, 'Perdeu'), (2, 'Ganhou'), (3, 'Ao Vivo')], default=0, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='game',
            name='can_be_modified_by_api',
            field=models.BooleanField(default=True, verbose_name='API pode modificar? '),
        ),
        migrations.AlterField(
            model_name='game',
            name='results_calculated',
            field=models.BooleanField(default=False, verbose_name='Resultados Calculados? '),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
