# Generated by Django 2.1.7 on 2019-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190502_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome da Cota'),
        ),
    ]
