# Generated by Django 2.0.6 on 2018-06-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180613_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='cotation_value_total',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cota Total da Aposta'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='core.Reward', verbose_name='Recompensa'),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Apostado'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='original_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Original'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Modificado'),
        ),
        migrations.AlterField(
            model_name='cotationhistory',
            name='original_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Original'),
        ),
        migrations.AlterField(
            model_name='cotationhistory',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='cotationhistory',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Modificado'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='who_rewarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller'),
        ),
    ]
