# Generated by Django 2.0.6 on 2018-06-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180613_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_championships', to='core.Country', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations', to='core.Game', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations', to='core.Market', verbose_name='Tipo da Cota'),
        ),
        migrations.AlterField(
            model_name='cotationhistory',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_history', to='core.Game', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='cotationhistory',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_history', to='core.Market', verbose_name='Tipo da Cota'),
        ),
        migrations.AlterField(
            model_name='game',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_games', to='core.Championship', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ft_score',
            field=models.CharField(blank=True, help_text='Placar final Ex: 3-5 (Casa-Visita)', max_length=80, null=True, verbose_name='Placar no final do Jogo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ht_score',
            field=models.CharField(blank=True, help_text='Placar meio-tempo Ex: 3-5 (Casa-Visita)', max_length=80, null=True, verbose_name='Placar até o meio-tempo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manager_was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Gerente foi pago?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='who_set_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Seller', verbose_name='Vendedor'),
        ),
    ]
