# Generated by Django 2.1.7 on 2019-05-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20190502_1517'),
        ('core', '0031_auto_20190503_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CotationHistory',
            new_name='CotationCopy',
        ),
    ]
