# Generated by Django 2.1.7 on 2019-05-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190506_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-pk',), 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
