# Generated by Django 2.0.6 on 2018-06-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180614_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='odds_calculated',
        ),
    ]
