# Generated by Django 2.0.6 on 2018-07-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_game_odds_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
