# Generated by Django 2.2.1 on 2019-05-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190513_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotation',
            options={'ordering': ['-pk'], 'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.AlterModelOptions(
            name='cotationcopy',
            options={'ordering': ['-pk'], 'verbose_name': 'Cota - Cópia', 'verbose_name_plural': 'Cotas - Cópia'},
        ),
        migrations.AlterModelOptions(
            name='cotationmodified',
            options={'ordering': ['-pk'], 'verbose_name': 'Cota Modificada', 'verbose_name_plural': 'Cotas Modificadas'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-pk',), 'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-pk'], 'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercados'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='cotation',
            name='start_price',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='base_line',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='game',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='line',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='market',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cotationcopy',
            name='start_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visible',
        ),
        migrations.AddField(
            model_name='game',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponível?'),
        ),
        migrations.AlterField(
            model_name='cotationmodified',
            name='cotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifiy', to='core.Cotation', verbose_name='Cota Original Modificada'),
        ),
        migrations.AlterField(
            model_name='cotationmodified',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifiy', to='core.Store', verbose_name='Banca'),
        ),
    ]
