# Generated by Django 2.0.6 on 2018-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180703_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
    ]
