# Generated by Django 2.2.1 on 2019-05-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190517_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='visible',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='visible',
            new_name='available',
        ),
    ]
