# Generated by Django 2.0.6 on 2018-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180707_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='status_reward',
            field=models.CharField(choices=[('Aguardando Resultados', 'Aguardando Resultados'), ('O apostador foi pago', 'O apostador foi pago'), ('Esse ticket não venceu', 'Esse ticket não venceu'), ('Venceu, Pagar Apostador', 'Venceu, Pagar Apostador')], default='Aguardando Resultados', max_length=80, verbose_name='Status do Prêmio'),
        ),
    ]
