# Generated by Django 2.2.2 on 2019-07-02 16:03

from django.db import migrations, models
import utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cotationcopy_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='config',
        ),
        migrations.AlterField(
            model_name='store',
            name='creation_date',
            field=models.DateTimeField(default=utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
