# Generated by Django 2.2.3 on 2019-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190702_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_full',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Placar Final'),
        ),
        migrations.AddField(
            model_name='game',
            name='score_half',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Placar Primeiro Tempo'),
        ),
    ]
