# Generated by Django 2.2.3 on 2019-07-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190705_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='can_be_modified_by_api',
        ),
    ]
