# Generated by Django 2.2.3 on 2019-07-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_game_can_be_modified_by_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueModified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridade')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifications', to='core.League', verbose_name='Liga Alterada')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_leagues_modifications', to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Liga Banca',
                'verbose_name_plural': 'Ligas da Banca',
                'ordering': ('-pk',),
            },
        ),
    ]
