# Generated by Django 2.2.3 on 2019-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_leaguemodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemodified',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Visível?'),
        ),
    ]
