# Generated by Django 2.2.3 on 2019-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_locationmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguemodified',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='locationmodified',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Prioridade'),
        ),
    ]
