# Generated by Django 2.2.3 on 2019-07-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190715_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodified',
            options={'ordering': ('-pk',), 'verbose_name': 'Países Banca', 'verbose_name_plural': 'Países da Banca'},
        ),
        migrations.AlterField(
            model_name='locationmodified',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifications', to='core.Location', verbose_name='País Alterado'),
        ),
        migrations.CreateModel(
            name='GameModified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Visível?')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifications', to='core.Game', verbose_name='Jogo Alterado')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games_modifications', to='core.Store', verbose_name='Banca')),
            ],
            options={
                'verbose_name': 'Países Banca',
                'verbose_name_plural': 'Países da Banca',
                'ordering': ('-pk',),
            },
        ),
    ]
