# Generated by Django 2.2.3 on 2019-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190717_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotationmodified',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
