# Generated by Django 2.2.3 on 2019-07-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_cotationmodified_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotationmodified',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
