# Generated by Django 2.2.4 on 2019-08-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190726_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotation',
            options={'ordering': ['-id'], 'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.AlterModelOptions(
            name='cotationcopy',
            options={'ordering': ['-id'], 'verbose_name': 'Cota - Cópia', 'verbose_name_plural': 'Cotas - Cópia'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-id',), 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-id',), 'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
    ]
