# Generated by Django 2.2.4 on 2019-08-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190820_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodified',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_modifications', to='core.Location', verbose_name='País Alterado'),
        ),
    ]
