# Generated by Django 2.2.4 on 2019-08-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20190821_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodified',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_modifications', to='core.Location', verbose_name='País Alterado'),
        ),
    ]
