# Generated by Django 2.2.4 on 2019-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20190821_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotationcopy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativa?'),
        ),
    ]
