# Generated by Django 2.2.4 on 2019-10-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20190919_1129'),
        ('core', '0051_cotationcopy_active'),
    ]

    operations = [
    ]
