# Generated by Django 2.2.6 on 2019-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_cotationcopy_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_in_zone',
            field=models.BooleanField(default=False, verbose_name='Zona de Destaque?'),
        ),
    ]
