# Generated by Django 2.2.6 on 2019-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_game_is_in_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodified',
            name='is_in_zone',
            field=models.BooleanField(default=False, verbose_name='Zona de Destaque?'),
        ),
    ]
