MARKET_ID = {
    1: "Vencedor do Encontro",
    10: "Casa/Visitante",
    37: "Vencedor do Primeiro Tempo",
    80: "Vencedor do Segundo Tempo", 
    976334: "Resultado/Total de Gol(s)",
    975916: "Resultado Exato no Primeiro Tempo",
    975909: "Resultado Exato do Jogo",
    976241: "Número Exato de Gol(s)",
    59: "Os Dois Times Marcam",
    976360: "Time Visitante Marca",
    976348: "Time da Casa Marca",
    976096: "Time da Casa NÃO Tomará Gol(s)",
    8594683: "Time Visitante NÃO Tomará Gol(s)",
    976204: "Total de Gols do Visitante",
    976198: "Total de Gols da Casa",
    12: "Total de Gol(s) no Encontro, Acima/Abaixo",
    47: "Total de Gol(s) no Segundo Tempo, Acima/Abaixo",
    38: "Total de Gols do Primeiro Tempo, Acima/Abaixo",
    976144: "Etapa com Mais Gol(s)",
    976316: "Resultado/2 Times Marcam",
    976193: "Vencedor nas Duas Etapas",
    63: "Dupla Chance",
    976236: "Vencer e não tomar Gol(s)",
    975930: "Placar Impar/Par",
}

MARKET_NAME_SMALL_TEAMS = {
    1: "Vencedor do Encontro",
    10: "Casa/Visitante",
    80: "Vencedor do Segundo Tempo",
    976334: "Resultado/Total de Gol(s)",
    975909: "Resultado Exato do Jogo",
    976241: "Número Exato de Gol(s)",
    59: "Os Dois Times Marcam",
    976360: "Time Visitante Marca",
    976348: "Time da Casa Marca",
    976096: "Time da Casa NÃO Tomará Gol(s)",
    8594683: "Time Visitante NÃO Tomará Gol(s)",
    976204: "Total de Gols do Visitante",
    976198: "Total de Gols da Casa",
    12: "Total de Gol(s) no Encontro, Acima/Abaixo",
    47: "Total de Gol(s) no Segundo Tempo, Acima/Abaixo",
    976316: "Resultado/2 Times Marcam",
    63: "Dupla Chance",
    976236: "Vencer e não tomar Gol(s)",
    975930: "Placar Impar/Par",
}


INVALID_ALL_COTES_CHAMPIONSHIPS = [
    1288,
    1289,
    1290,
    1291,
    1292,
    1293,
    1294,
    1295,
    1298,
    1299,
    1300,
    1301,
    1302,
    1303,
    1304,
    1305,
    1306,
    1307,
    1308,
    1309,
    1310,
    1311,
    1312,
    1314,
    1315,
    1316,
    1317,
    1318,
    1319,
    1320,
    1321,
    1322,
    1323,
    1324,
    1385,
    1386,
    1456,
    1345,
    357,
    642,
    1082,
]


COUNTRY_TRANSLATE = {
	"Brazil":"Brasil",
	"England":"Inglaterra",
	"Spain":"Espanha",
	"France":"França",
	"Germany":"Alemanha",
	"Italy":"Itália",
	"Portugal":"Portugal",
	"Belgium":"Bélgica",
	"USA":"Estados Unidos",
	"Turkey":"Turquia",
	"Netherlands":"Holanda",
	"Russia":"Rússia",
	"Austria":"Áustria",
	"Poland":"Polônia",
	"Angola":"Ângola",
	"Albania":"Albânia",
	"Croatia":"Croácia",
	"Sweden":"Suécia",
	"Malta":"Malta",
	"Saudi Arabia":"Arábia Saudita",
	"Israel":"Israel",
	"Denmark":"Dinamarca",
	"Hong Kong":"Hong Kong",
	"United Arab Emirates":"Emirados Árabes",
	"Finland":"Finlândia",
	"Norway":"Noruega",
	"Greece":"Grécia",
	"Switzerland": "Suíça",
	"Mexico":"México",
	"Ecuador":"Equador",
	"Scotland":"Escócia",
	"Iceland":"Islândia",
	"Saudi Arabia": "Arábia Saudita",
	"India":"Índia",
	"Côte d'Ivoire":"Costa do Marfim",
	"Ukraine":"Ucrânia",
	"Iraq":"Iraque",
	"Cyprus":"Chipre",
	"Georgia":"Geórgia",
	"South Africa":"África do Sul",
	"Romania":"Romênia",
	"Uruguay":"Uruguai",
	"Republic of Ireland":"Irlanda",
	"Bulgaria":"Bulgária",
	"Belarus":"Bielorrússia",
	"Serbia":"Sérvia",
	"Japan":"Japão",
	"Wales":"País de Gales",
	"Cameroon":"Camarões",
	"Egypt":"Egito",
	"Paraguay":"Paraguai",
	"Lithuania":"Lituânia",
	"Estonia":"Estónia",
	"Panama":"Panamá",
	"Indonesia":"Indonésia",
    "Hungary": "Hungria",
    "Czech Republic": "República Checa",
    "South Korea": "Coreia do Sul",
    "Korea Republic": "Coreia do Sul",
    "Ghana":"Gana",
    "Morocco":"Marrocos",
    "Iran":"Irã",
    "Tunisia":"Tunísia",
}